# WebAPI Generator Configuration

idl_dir = "node_modules/@webref/idl"
output_dir = "../src"
templates_dir = "base.mbt"

core_specs = [
    "cssom",
    "cssom-view",
    "dom",
    "fetch",
    "html",
    "hr-time",
    "geometry",
    "FileAPI",
    "performance-timeline",
    "referrer-policy",
    "SVG",
    "trusted-types",
    "uievents",
    "url",
    "webidl",
    "xhr",
]

excluded_interfaces = ["ShadowAnimation", "OffscreenRenderingContext"]

excluded_callbacks = []

excluded_typedefs = []

excluded_dictionary_prefixes = []
