# WebAPI Generator Configuration

idl_dir = "../node_modules/@webref/idl"
output_dir = "../src"
templates_dir = "base.mbt"

core_specs = [
    "dom",
    "html",
    "uievents",
    "cssom",
    "cssom-view",
    "geometry",
    "FileAPI",
    "SVG",
    "xhr",
    "webidl",
]

excluded_interfaces = []

excluded_callbacks = []

excluded_typedefs = []

excluded_dictionary_prefixes = []
