[Exposed=Window]
interface HTMLParagraphElement : HTMLElement {
  [HTMLConstructor] constructor();

  // also has obsolete members
};

partial interface HTMLParagraphElement {
  [CEReactions, Reflect] attribute DOMString align;
};
