[Exposed=Window]
interface HTMLDivElement : HTMLElement {
  [HTMLConstructor] constructor();

  // also has obsolete members
};

partial interface HTMLDivElement {
  [CEReactions, Reflect] attribute DOMString align;
};
