[Exposed=Window]
interface HTMLHtmlElement : HTMLElement {
  [HTMLConstructor] constructor();

  // also has obsolete members
};

partial interface HTMLHtmlElement {
  [CEReactions, Reflect] attribute DOMString version;
};
