fn dom_quad_init_ffi(p1: JsValue, p2: JsValue, p3: JsValue, p4: JsValue) -> DOMQuadInit = "webapi_DOMQuadInit" "new"

fn dom_quad_init_empty_ffi() -> DOMQuadInit = "webapi_Dictionary" "empty"

fn dom_quad_init_get_p1_ffi(obj: JsValue) -> JsValue = "webapi_DOMQuadInit" "get_p1"

fn dom_quad_init_get_p2_ffi(obj: JsValue) -> JsValue = "webapi_DOMQuadInit" "get_p2"

fn dom_quad_init_get_p3_ffi(obj: JsValue) -> JsValue = "webapi_DOMQuadInit" "get_p3"

fn dom_quad_init_get_p4_ffi(obj: JsValue) -> JsValue = "webapi_DOMQuadInit" "get_p4"