fn keyframe_effect_options_ffi(fill: JsValue, iteration_start: JsValue, iterations: JsValue, direction: JsValue, easing: JsValue, delay: JsValue, end_delay: JsValue, duration: JsValue, composite: JsValue, pseudo_element: JsValue) -> KeyframeEffectOptions = "webapi_KeyframeEffectOptions" "new"

fn keyframe_effect_options_empty_ffi() -> KeyframeEffectOptions = "webapi_Dictionary" "empty"

fn keyframe_effect_options_get_fill_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_fill"

fn keyframe_effect_options_get_iteration_start_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_iterationStart"

fn keyframe_effect_options_get_iterations_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_iterations"

fn keyframe_effect_options_get_direction_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_direction"

fn keyframe_effect_options_get_easing_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_easing"

fn keyframe_effect_options_get_delay_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_delay"

fn keyframe_effect_options_get_end_delay_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_endDelay"

fn keyframe_effect_options_get_duration_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_duration"

fn keyframe_effect_options_get_composite_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_composite"

fn keyframe_effect_options_get_pseudo_element_ffi(obj: JsValue) -> JsValue = "webapi_KeyframeEffectOptions" "get_pseudoElement"