fn css_page_descriptors_margin_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_margin"

fn css_page_descriptors_set_margin_ffi(obj: JsValue, margin: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_margin"

fn css_page_descriptors_margin_top_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_marginTop"

fn css_page_descriptors_set_margin_top_ffi(obj: JsValue, margin_top: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_marginTop"

fn css_page_descriptors_margin_right_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_marginRight"

fn css_page_descriptors_set_margin_right_ffi(obj: JsValue, margin_right: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_marginRight"

fn css_page_descriptors_margin_bottom_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_marginBottom"

fn css_page_descriptors_set_margin_bottom_ffi(obj: JsValue, margin_bottom: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_marginBottom"

fn css_page_descriptors_margin_left_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_marginLeft"

fn css_page_descriptors_set_margin_left_ffi(obj: JsValue, margin_left: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_marginLeft"

fn css_page_descriptors_size_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_size"

fn css_page_descriptors_set_size_ffi(obj: JsValue, size: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_size"

fn css_page_descriptors_page_orientation_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_pageOrientation"

fn css_page_descriptors_set_page_orientation_ffi(obj: JsValue, page_orientation: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_pageOrientation"

fn css_page_descriptors_marks_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_marks"

fn css_page_descriptors_set_marks_ffi(obj: JsValue, marks: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_marks"

fn css_page_descriptors_bleed_ffi(obj: JsValue) -> JsValue = "webapi_CSSPageDescriptors" "get_bleed"

fn css_page_descriptors_set_bleed_ffi(obj: JsValue, bleed: JsValue) -> Unit = "webapi_CSSPageDescriptors" "set_bleed"