fn dom_point_read_only_new_ffi(x: JsValue, y: JsValue, z: JsValue, w: JsValue) -> DOMPointReadOnly = "webapi_DOMPointReadOnly" "new"

fn dom_point_read_only_from_point_ffi(other: JsValue) -> JsValue = "webapi_DOMPointReadOnly" "fromPoint"

fn dom_point_read_only_x_ffi(obj: JsValue) -> JsValue = "webapi_DOMPointReadOnly" "get_x"

fn dom_point_read_only_y_ffi(obj: JsValue) -> JsValue = "webapi_DOMPointReadOnly" "get_y"

fn dom_point_read_only_z_ffi(obj: JsValue) -> JsValue = "webapi_DOMPointReadOnly" "get_z"

fn dom_point_read_only_w_ffi(obj: JsValue) -> JsValue = "webapi_DOMPointReadOnly" "get_w"

fn dom_point_read_only_matrix_transform_ffi(obj: JsValue, matrix: JsValue) -> JsValue = "webapi_DOMPointReadOnly" "matrixTransform"

fn dom_point_read_only_to_json_ffi(obj: JsValue) -> JsValue = "webapi_DOMPointReadOnly" "toJSON"