fn dom_matrix_new_ffi(init: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "new"

fn dom_matrix_from_matrix_ffi(other: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "fromMatrix"

fn dom_matrix_from_float32array_ffi(array32: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "fromFloat32Array"

fn dom_matrix_from_float64array_ffi(array64: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "fromFloat64Array"

fn dom_matrix_a_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_a"

fn dom_matrix_set_a_ffi(obj: JsValue, a: JsValue) -> Unit = "webapi_DOMMatrix" "set_a"

fn dom_matrix_b_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_b"

fn dom_matrix_set_b_ffi(obj: JsValue, b: JsValue) -> Unit = "webapi_DOMMatrix" "set_b"

fn dom_matrix_c_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_c"

fn dom_matrix_set_c_ffi(obj: JsValue, c: JsValue) -> Unit = "webapi_DOMMatrix" "set_c"

fn dom_matrix_d_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_d"

fn dom_matrix_set_d_ffi(obj: JsValue, d: JsValue) -> Unit = "webapi_DOMMatrix" "set_d"

fn dom_matrix_e_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_e"

fn dom_matrix_set_e_ffi(obj: JsValue, e: JsValue) -> Unit = "webapi_DOMMatrix" "set_e"

fn dom_matrix_f_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_f"

fn dom_matrix_set_f_ffi(obj: JsValue, f: JsValue) -> Unit = "webapi_DOMMatrix" "set_f"

fn dom_matrix_m11_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m11"

fn dom_matrix_set_m11_ffi(obj: JsValue, m11: JsValue) -> Unit = "webapi_DOMMatrix" "set_m11"

fn dom_matrix_m12_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m12"

fn dom_matrix_set_m12_ffi(obj: JsValue, m12: JsValue) -> Unit = "webapi_DOMMatrix" "set_m12"

fn dom_matrix_m13_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m13"

fn dom_matrix_set_m13_ffi(obj: JsValue, m13: JsValue) -> Unit = "webapi_DOMMatrix" "set_m13"

fn dom_matrix_m14_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m14"

fn dom_matrix_set_m14_ffi(obj: JsValue, m14: JsValue) -> Unit = "webapi_DOMMatrix" "set_m14"

fn dom_matrix_m21_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m21"

fn dom_matrix_set_m21_ffi(obj: JsValue, m21: JsValue) -> Unit = "webapi_DOMMatrix" "set_m21"

fn dom_matrix_m22_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m22"

fn dom_matrix_set_m22_ffi(obj: JsValue, m22: JsValue) -> Unit = "webapi_DOMMatrix" "set_m22"

fn dom_matrix_m23_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m23"

fn dom_matrix_set_m23_ffi(obj: JsValue, m23: JsValue) -> Unit = "webapi_DOMMatrix" "set_m23"

fn dom_matrix_m24_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m24"

fn dom_matrix_set_m24_ffi(obj: JsValue, m24: JsValue) -> Unit = "webapi_DOMMatrix" "set_m24"

fn dom_matrix_m31_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m31"

fn dom_matrix_set_m31_ffi(obj: JsValue, m31: JsValue) -> Unit = "webapi_DOMMatrix" "set_m31"

fn dom_matrix_m32_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m32"

fn dom_matrix_set_m32_ffi(obj: JsValue, m32: JsValue) -> Unit = "webapi_DOMMatrix" "set_m32"

fn dom_matrix_m33_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m33"

fn dom_matrix_set_m33_ffi(obj: JsValue, m33: JsValue) -> Unit = "webapi_DOMMatrix" "set_m33"

fn dom_matrix_m34_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m34"

fn dom_matrix_set_m34_ffi(obj: JsValue, m34: JsValue) -> Unit = "webapi_DOMMatrix" "set_m34"

fn dom_matrix_m41_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m41"

fn dom_matrix_set_m41_ffi(obj: JsValue, m41: JsValue) -> Unit = "webapi_DOMMatrix" "set_m41"

fn dom_matrix_m42_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m42"

fn dom_matrix_set_m42_ffi(obj: JsValue, m42: JsValue) -> Unit = "webapi_DOMMatrix" "set_m42"

fn dom_matrix_m43_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m43"

fn dom_matrix_set_m43_ffi(obj: JsValue, m43: JsValue) -> Unit = "webapi_DOMMatrix" "set_m43"

fn dom_matrix_m44_ffi(obj: JsValue) -> Double = "webapi_DOMMatrix" "get_m44"

fn dom_matrix_set_m44_ffi(obj: JsValue, m44: JsValue) -> Unit = "webapi_DOMMatrix" "set_m44"

fn dom_matrix_multiply_self_ffi(obj: JsValue, other: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "multiplySelf"

fn dom_matrix_pre_multiply_self_ffi(obj: JsValue, other: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "preMultiplySelf"

fn dom_matrix_translate_self_ffi(obj: JsValue, tx: JsValue, ty: JsValue, tz: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "translateSelf"

fn dom_matrix_scale_self_ffi(obj: JsValue, scale_x: JsValue, scale_y: JsValue, scale_z: JsValue, origin_x: JsValue, origin_y: JsValue, origin_z: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "scaleSelf"

fn dom_matrix_scale3d_self_ffi(obj: JsValue, scale: JsValue, origin_x: JsValue, origin_y: JsValue, origin_z: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "scale3dSelf"

fn dom_matrix_rotate_self_ffi(obj: JsValue, rot_x: JsValue, rot_y: JsValue, rot_z: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "rotateSelf"

fn dom_matrix_rotate_from_vector_self_ffi(obj: JsValue, x: JsValue, y: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "rotateFromVectorSelf"

fn dom_matrix_rotate_axis_angle_self_ffi(obj: JsValue, x: JsValue, y: JsValue, z: JsValue, angle: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "rotateAxisAngleSelf"

fn dom_matrix_skew_x_self_ffi(obj: JsValue, sx: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "skewXSelf"

fn dom_matrix_skew_y_self_ffi(obj: JsValue, sy: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "skewYSelf"

fn dom_matrix_invert_self_ffi(obj: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "invertSelf"

fn dom_matrix_set_matrix_value_ffi(obj: JsValue, transform_list: JsValue) -> DOMMatrix = "webapi_DOMMatrix" "setMatrixValue"