fn html_anchor_element_new_ffi() -> HTMLAnchorElement = "webapi_HTMLAnchorElement" "new"

fn html_anchor_element_target_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_target"

///|
fn html_anchor_element_target_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_target_ffi_wasm(obj))
}

fn html_anchor_element_set_target_ffi(obj: JsValue, target: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_target"

fn html_anchor_element_download_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_download"

///|
fn html_anchor_element_download_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_download_ffi_wasm(obj))
}

fn html_anchor_element_set_download_ffi(obj: JsValue, download: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_download"

fn html_anchor_element_ping_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_ping"

///|
fn html_anchor_element_ping_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_ping_ffi_wasm(obj))
}

fn html_anchor_element_set_ping_ffi(obj: JsValue, ping: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_ping"

fn html_anchor_element_rel_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_rel"

///|
fn html_anchor_element_rel_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_rel_ffi_wasm(obj))
}

fn html_anchor_element_set_rel_ffi(obj: JsValue, rel: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_rel"

fn html_anchor_element_rel_list_ffi(obj: JsValue) -> DOMTokenList = "webapi_HTMLAnchorElement" "get_relList"

fn html_anchor_element_hreflang_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_hreflang"

///|
fn html_anchor_element_hreflang_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_hreflang_ffi_wasm(obj))
}

fn html_anchor_element_set_hreflang_ffi(obj: JsValue, hreflang: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_hreflang"

fn html_anchor_element_type_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_type"

///|
fn html_anchor_element_type_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_type_ffi_wasm(obj))
}

fn html_anchor_element_set_type_ffi(obj: JsValue, type_: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_type"

fn html_anchor_element_text_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_text"

///|
fn html_anchor_element_text_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_text_ffi_wasm(obj))
}

fn html_anchor_element_set_text_ffi(obj: JsValue, text: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_text"

fn html_anchor_element_referrer_policy_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_referrerPolicy"

///|
fn html_anchor_element_referrer_policy_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_referrer_policy_ffi_wasm(obj))
}

fn html_anchor_element_set_referrer_policy_ffi(obj: JsValue, referrer_policy: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_referrerPolicy"

fn html_anchor_element_coords_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_coords"

///|
fn html_anchor_element_coords_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_coords_ffi_wasm(obj))
}

fn html_anchor_element_set_coords_ffi(obj: JsValue, coords: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_coords"

fn html_anchor_element_charset_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_charset"

///|
fn html_anchor_element_charset_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_charset_ffi_wasm(obj))
}

fn html_anchor_element_set_charset_ffi(obj: JsValue, charset: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_charset"

fn html_anchor_element_name_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_name"

///|
fn html_anchor_element_name_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_name_ffi_wasm(obj))
}

fn html_anchor_element_set_name_ffi(obj: JsValue, name: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_name"

fn html_anchor_element_rev_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_rev"

///|
fn html_anchor_element_rev_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_rev_ffi_wasm(obj))
}

fn html_anchor_element_set_rev_ffi(obj: JsValue, rev: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_rev"

fn html_anchor_element_shape_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_shape"

///|
fn html_anchor_element_shape_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_shape_ffi_wasm(obj))
}

fn html_anchor_element_set_shape_ffi(obj: JsValue, shape: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_shape"

fn html_anchor_element_href_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_href"

///|
fn html_anchor_element_href_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_href_ffi_wasm(obj))
}

fn html_anchor_element_set_href_ffi(obj: JsValue, href: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_href"

fn html_anchor_element_origin_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_origin"

///|
fn html_anchor_element_origin_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_origin_ffi_wasm(obj))
}

fn html_anchor_element_protocol_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_protocol"

///|
fn html_anchor_element_protocol_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_protocol_ffi_wasm(obj))
}

fn html_anchor_element_set_protocol_ffi(obj: JsValue, protocol: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_protocol"

fn html_anchor_element_username_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_username"

///|
fn html_anchor_element_username_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_username_ffi_wasm(obj))
}

fn html_anchor_element_set_username_ffi(obj: JsValue, username: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_username"

fn html_anchor_element_password_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_password"

///|
fn html_anchor_element_password_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_password_ffi_wasm(obj))
}

fn html_anchor_element_set_password_ffi(obj: JsValue, password: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_password"

fn html_anchor_element_host_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_host"

///|
fn html_anchor_element_host_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_host_ffi_wasm(obj))
}

fn html_anchor_element_set_host_ffi(obj: JsValue, host: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_host"

fn html_anchor_element_hostname_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_hostname"

///|
fn html_anchor_element_hostname_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_hostname_ffi_wasm(obj))
}

fn html_anchor_element_set_hostname_ffi(obj: JsValue, hostname: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_hostname"

fn html_anchor_element_port_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_port"

///|
fn html_anchor_element_port_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_port_ffi_wasm(obj))
}

fn html_anchor_element_set_port_ffi(obj: JsValue, port: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_port"

fn html_anchor_element_pathname_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_pathname"

///|
fn html_anchor_element_pathname_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_pathname_ffi_wasm(obj))
}

fn html_anchor_element_set_pathname_ffi(obj: JsValue, pathname: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_pathname"

fn html_anchor_element_search_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_search"

///|
fn html_anchor_element_search_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_search_ffi_wasm(obj))
}

fn html_anchor_element_set_search_ffi(obj: JsValue, search: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_search"

fn html_anchor_element_hash_ffi_wasm(obj: JsValue) -> JsValue = "webapi_HTMLAnchorElement" "get_hash"

///|
fn html_anchor_element_hash_ffi(obj: JsValue) -> String {
  jsvalue_to_string(html_anchor_element_hash_ffi_wasm(obj))
}

fn html_anchor_element_set_hash_ffi(obj: JsValue, hash: JsValue) -> Unit = "webapi_HTMLAnchorElement" "set_hash"