///|
fn html_meter_element_new_ffi() -> HTMLMeterElement = "webapi_HTMLMeterElement" "new"

///|
fn html_meter_element_value_ffi(obj : JsValue) -> Double = "webapi_HTMLMeterElement" "get_value"

///|
fn html_meter_element_set_value_ffi(obj : JsValue, value : JsValue) -> Unit = "webapi_HTMLMeterElement" "set_value"

///|
fn html_meter_element_min_ffi(obj : JsValue) -> Double = "webapi_HTMLMeterElement" "get_min"

///|
fn html_meter_element_set_min_ffi(obj : JsValue, min : JsValue) -> Unit = "webapi_HTMLMeterElement" "set_min"

///|
fn html_meter_element_max_ffi(obj : JsValue) -> Double = "webapi_HTMLMeterElement" "get_max"

///|
fn html_meter_element_set_max_ffi(obj : JsValue, max : JsValue) -> Unit = "webapi_HTMLMeterElement" "set_max"

///|
fn html_meter_element_low_ffi(obj : JsValue) -> Double = "webapi_HTMLMeterElement" "get_low"

///|
fn html_meter_element_set_low_ffi(obj : JsValue, low : JsValue) -> Unit = "webapi_HTMLMeterElement" "set_low"

///|
fn html_meter_element_high_ffi(obj : JsValue) -> Double = "webapi_HTMLMeterElement" "get_high"

///|
fn html_meter_element_set_high_ffi(obj : JsValue, high : JsValue) -> Unit = "webapi_HTMLMeterElement" "set_high"

///|
fn html_meter_element_optimum_ffi(obj : JsValue) -> Double = "webapi_HTMLMeterElement" "get_optimum"

///|
fn html_meter_element_set_optimum_ffi(obj : JsValue, optimum : JsValue) -> Unit = "webapi_HTMLMeterElement" "set_optimum"

///|
fn html_meter_element_labels_ffi(obj : JsValue) -> NodeList = "webapi_HTMLMeterElement" "get_labels"
