///|
fn html_option_element_new_ffi() -> HTMLOptionElement = "webapi_HTMLOptionElement" "new"

///|
fn html_option_element_disabled_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_disabled"

///|
fn html_option_element_set_disabled_ffi(
  obj : JsValue,
  disabled : JsValue,
) -> Unit = "webapi_HTMLOptionElement" "set_disabled"

///|
fn html_option_element_form_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_form"

///|
fn html_option_element_label_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_label"

///|
fn html_option_element_set_label_ffi(obj : JsValue, label : JsValue) -> Unit = "webapi_HTMLOptionElement" "set_label"

///|
fn html_option_element_default_selected_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_defaultSelected"

///|
fn html_option_element_set_default_selected_ffi(
  obj : JsValue,
  default_selected : JsValue,
) -> Unit = "webapi_HTMLOptionElement" "set_defaultSelected"

///|
fn html_option_element_selected_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_selected"

///|
fn html_option_element_set_selected_ffi(
  obj : JsValue,
  selected : JsValue,
) -> Unit = "webapi_HTMLOptionElement" "set_selected"

///|
fn html_option_element_value_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_value"

///|
fn html_option_element_set_value_ffi(obj : JsValue, value : JsValue) -> Unit = "webapi_HTMLOptionElement" "set_value"

///|
fn html_option_element_text_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_text"

///|
fn html_option_element_set_text_ffi(obj : JsValue, text : JsValue) -> Unit = "webapi_HTMLOptionElement" "set_text"

///|
fn html_option_element_index_ffi(obj : JsValue) -> JsValue = "webapi_HTMLOptionElement" "get_index"
