///|
fn offscreen_canvas_rendering_context2d_canvas_ffi(obj : JsValue) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_canvas"

///|
fn offscreen_canvas_rendering_context2d_get_context_attributes_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "getContextAttributes"

///|
fn offscreen_canvas_rendering_context2d_save_ffi(obj : JsValue) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "save"

///|
fn offscreen_canvas_rendering_context2d_restore_ffi(obj : JsValue) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "restore"

///|
fn offscreen_canvas_rendering_context2d_reset_ffi(obj : JsValue) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "reset"

///|
fn offscreen_canvas_rendering_context2d_is_context_lost_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "isContextLost"

///|
fn offscreen_canvas_rendering_context2d_scale_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "scale"

///|
fn offscreen_canvas_rendering_context2d_rotate_ffi(
  obj : JsValue,
  angle : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "rotate"

///|
fn offscreen_canvas_rendering_context2d_translate_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "translate"

///|
fn offscreen_canvas_rendering_context2d_transform_ffi(
  obj : JsValue,
  a : JsValue,
  b : JsValue,
  c : JsValue,
  d : JsValue,
  e : JsValue,
  f : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "transform"

///|
fn offscreen_canvas_rendering_context2d_get_transform_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "getTransform"

///|
fn offscreen_canvas_rendering_context2d_set_transform_ffi(
  obj : JsValue,
  a : JsValue,
  b : JsValue,
  c : JsValue,
  d : JsValue,
  e : JsValue,
  f : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "setTransform"

///|
fn offscreen_canvas_rendering_context2d_set_transform_2_ffi(
  obj : JsValue,
  transform : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "setTransform_2"

///|
fn offscreen_canvas_rendering_context2d_reset_transform_ffi(
  obj : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "resetTransform"

///|
fn offscreen_canvas_rendering_context2d_global_alpha_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_globalAlpha"

///|
fn offscreen_canvas_rendering_context2d_set_global_alpha_ffi(
  obj : JsValue,
  global_alpha : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_globalAlpha"

///|
fn offscreen_canvas_rendering_context2d_global_composite_operation_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_globalCompositeOperation"

///|
fn offscreen_canvas_rendering_context2d_set_global_composite_operation_ffi(
  obj : JsValue,
  global_composite_operation : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_globalCompositeOperation"

///|
fn offscreen_canvas_rendering_context2d_image_smoothing_enabled_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_imageSmoothingEnabled"

///|
fn offscreen_canvas_rendering_context2d_set_image_smoothing_enabled_ffi(
  obj : JsValue,
  image_smoothing_enabled : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_imageSmoothingEnabled"

///|
fn offscreen_canvas_rendering_context2d_image_smoothing_quality_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_imageSmoothingQuality"

///|
fn offscreen_canvas_rendering_context2d_set_image_smoothing_quality_ffi(
  obj : JsValue,
  image_smoothing_quality : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_imageSmoothingQuality"

///|
fn offscreen_canvas_rendering_context2d_stroke_style_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_strokeStyle"

///|
fn offscreen_canvas_rendering_context2d_set_stroke_style_ffi(
  obj : JsValue,
  stroke_style : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_strokeStyle"

///|
fn offscreen_canvas_rendering_context2d_fill_style_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_fillStyle"

///|
fn offscreen_canvas_rendering_context2d_set_fill_style_ffi(
  obj : JsValue,
  fill_style : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_fillStyle"

///|
fn offscreen_canvas_rendering_context2d_create_linear_gradient_ffi(
  obj : JsValue,
  x0 : JsValue,
  y0 : JsValue,
  x1 : JsValue,
  y1 : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "createLinearGradient"

///|
fn offscreen_canvas_rendering_context2d_create_radial_gradient_ffi(
  obj : JsValue,
  x0 : JsValue,
  y0 : JsValue,
  r0 : JsValue,
  x1 : JsValue,
  y1 : JsValue,
  r1 : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "createRadialGradient"

///|
fn offscreen_canvas_rendering_context2d_create_conic_gradient_ffi(
  obj : JsValue,
  start_angle : JsValue,
  x : JsValue,
  y : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "createConicGradient"

///|
fn offscreen_canvas_rendering_context2d_create_pattern_ffi(
  obj : JsValue,
  image : JsValue,
  repetition : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "createPattern"

///|
fn offscreen_canvas_rendering_context2d_shadow_offset_x_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_shadowOffsetX"

///|
fn offscreen_canvas_rendering_context2d_set_shadow_offset_x_ffi(
  obj : JsValue,
  shadow_offset_x : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_shadowOffsetX"

///|
fn offscreen_canvas_rendering_context2d_shadow_offset_y_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_shadowOffsetY"

///|
fn offscreen_canvas_rendering_context2d_set_shadow_offset_y_ffi(
  obj : JsValue,
  shadow_offset_y : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_shadowOffsetY"

///|
fn offscreen_canvas_rendering_context2d_shadow_blur_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_shadowBlur"

///|
fn offscreen_canvas_rendering_context2d_set_shadow_blur_ffi(
  obj : JsValue,
  shadow_blur : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_shadowBlur"

///|
fn offscreen_canvas_rendering_context2d_shadow_color_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_shadowColor"

///|
fn offscreen_canvas_rendering_context2d_set_shadow_color_ffi(
  obj : JsValue,
  shadow_color : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_shadowColor"

///|
fn offscreen_canvas_rendering_context2d_filter_ffi(obj : JsValue) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_filter"

///|
fn offscreen_canvas_rendering_context2d_set_filter_ffi(
  obj : JsValue,
  filter : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_filter"

///|
fn offscreen_canvas_rendering_context2d_clear_rect_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  w : JsValue,
  h : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "clearRect"

///|
fn offscreen_canvas_rendering_context2d_fill_rect_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  w : JsValue,
  h : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "fillRect"

///|
fn offscreen_canvas_rendering_context2d_stroke_rect_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  w : JsValue,
  h : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "strokeRect"

///|
fn offscreen_canvas_rendering_context2d_begin_path_ffi(obj : JsValue) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "beginPath"

///|
fn offscreen_canvas_rendering_context2d_fill_ffi(
  obj : JsValue,
  fill_rule : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "fill"

///|
fn offscreen_canvas_rendering_context2d_fill_2_ffi(
  obj : JsValue,
  path : JsValue,
  fill_rule : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "fill_2"

///|
fn offscreen_canvas_rendering_context2d_stroke_ffi(obj : JsValue) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "stroke"

///|
fn offscreen_canvas_rendering_context2d_stroke_2_ffi(
  obj : JsValue,
  path : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "stroke_2"

///|
fn offscreen_canvas_rendering_context2d_clip_ffi(
  obj : JsValue,
  fill_rule : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "clip"

///|
fn offscreen_canvas_rendering_context2d_clip_2_ffi(
  obj : JsValue,
  path : JsValue,
  fill_rule : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "clip_2"

///|
fn offscreen_canvas_rendering_context2d_is_point_in_path_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  fill_rule : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "isPointInPath"

///|
fn offscreen_canvas_rendering_context2d_is_point_in_path_2_ffi(
  obj : JsValue,
  path : JsValue,
  x : JsValue,
  y : JsValue,
  fill_rule : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "isPointInPath_2"

///|
fn offscreen_canvas_rendering_context2d_is_point_in_stroke_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "isPointInStroke"

///|
fn offscreen_canvas_rendering_context2d_is_point_in_stroke_2_ffi(
  obj : JsValue,
  path : JsValue,
  x : JsValue,
  y : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "isPointInStroke_2"

///|
fn offscreen_canvas_rendering_context2d_fill_text_ffi(
  obj : JsValue,
  text : JsValue,
  x : JsValue,
  y : JsValue,
  max_width : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "fillText"

///|
fn offscreen_canvas_rendering_context2d_stroke_text_ffi(
  obj : JsValue,
  text : JsValue,
  x : JsValue,
  y : JsValue,
  max_width : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "strokeText"

///|
fn offscreen_canvas_rendering_context2d_measure_text_ffi(
  obj : JsValue,
  text : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "measureText"

///|
fn offscreen_canvas_rendering_context2d_draw_image_ffi(
  obj : JsValue,
  image : JsValue,
  dx : JsValue,
  dy : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "drawImage"

///|
fn offscreen_canvas_rendering_context2d_draw_image_2_ffi(
  obj : JsValue,
  image : JsValue,
  dx : JsValue,
  dy : JsValue,
  dw : JsValue,
  dh : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "drawImage_2"

///|
fn offscreen_canvas_rendering_context2d_draw_image_3_ffi(
  obj : JsValue,
  image : JsValue,
  sx : JsValue,
  sy : JsValue,
  sw : JsValue,
  sh : JsValue,
  dx : JsValue,
  dy : JsValue,
  dw : JsValue,
  dh : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "drawImage_3"

///|
fn offscreen_canvas_rendering_context2d_create_image_data_ffi(
  obj : JsValue,
  sw : JsValue,
  sh : JsValue,
  settings : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "createImageData"

///|
fn offscreen_canvas_rendering_context2d_create_image_data_2_ffi(
  obj : JsValue,
  image_data : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "createImageData_2"

///|
fn offscreen_canvas_rendering_context2d_get_image_data_ffi(
  obj : JsValue,
  sx : JsValue,
  sy : JsValue,
  sw : JsValue,
  sh : JsValue,
  settings : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "getImageData"

///|
fn offscreen_canvas_rendering_context2d_put_image_data_ffi(
  obj : JsValue,
  image_data : JsValue,
  dx : JsValue,
  dy : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "putImageData"

///|
fn offscreen_canvas_rendering_context2d_put_image_data_2_ffi(
  obj : JsValue,
  image_data : JsValue,
  dx : JsValue,
  dy : JsValue,
  dirty_x : JsValue,
  dirty_y : JsValue,
  dirty_width : JsValue,
  dirty_height : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "putImageData_2"

///|
fn offscreen_canvas_rendering_context2d_line_width_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_lineWidth"

///|
fn offscreen_canvas_rendering_context2d_set_line_width_ffi(
  obj : JsValue,
  line_width : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_lineWidth"

///|
fn offscreen_canvas_rendering_context2d_line_cap_ffi(obj : JsValue) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_lineCap"

///|
fn offscreen_canvas_rendering_context2d_set_line_cap_ffi(
  obj : JsValue,
  line_cap : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_lineCap"

///|
fn offscreen_canvas_rendering_context2d_line_join_ffi(obj : JsValue) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_lineJoin"

///|
fn offscreen_canvas_rendering_context2d_set_line_join_ffi(
  obj : JsValue,
  line_join : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_lineJoin"

///|
fn offscreen_canvas_rendering_context2d_miter_limit_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_miterLimit"

///|
fn offscreen_canvas_rendering_context2d_set_miter_limit_ffi(
  obj : JsValue,
  miter_limit : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_miterLimit"

///|
fn offscreen_canvas_rendering_context2d_set_line_dash_ffi(
  obj : JsValue,
  segments : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "setLineDash"

///|
fn offscreen_canvas_rendering_context2d_get_line_dash_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "getLineDash"

///|
fn offscreen_canvas_rendering_context2d_line_dash_offset_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_lineDashOffset"

///|
fn offscreen_canvas_rendering_context2d_set_line_dash_offset_ffi(
  obj : JsValue,
  line_dash_offset : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_lineDashOffset"

///|
fn offscreen_canvas_rendering_context2d_lang_ffi(obj : JsValue) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_lang"

///|
fn offscreen_canvas_rendering_context2d_set_lang_ffi(
  obj : JsValue,
  lang : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_lang"

///|
fn offscreen_canvas_rendering_context2d_font_ffi(obj : JsValue) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_font"

///|
fn offscreen_canvas_rendering_context2d_set_font_ffi(
  obj : JsValue,
  font : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_font"

///|
fn offscreen_canvas_rendering_context2d_text_align_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_textAlign"

///|
fn offscreen_canvas_rendering_context2d_set_text_align_ffi(
  obj : JsValue,
  text_align : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_textAlign"

///|
fn offscreen_canvas_rendering_context2d_text_baseline_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_textBaseline"

///|
fn offscreen_canvas_rendering_context2d_set_text_baseline_ffi(
  obj : JsValue,
  text_baseline : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_textBaseline"

///|
fn offscreen_canvas_rendering_context2d_direction_ffi(obj : JsValue) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_direction"

///|
fn offscreen_canvas_rendering_context2d_set_direction_ffi(
  obj : JsValue,
  direction : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_direction"

///|
fn offscreen_canvas_rendering_context2d_letter_spacing_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_letterSpacing"

///|
fn offscreen_canvas_rendering_context2d_set_letter_spacing_ffi(
  obj : JsValue,
  letter_spacing : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_letterSpacing"

///|
fn offscreen_canvas_rendering_context2d_font_kerning_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_fontKerning"

///|
fn offscreen_canvas_rendering_context2d_set_font_kerning_ffi(
  obj : JsValue,
  font_kerning : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_fontKerning"

///|
fn offscreen_canvas_rendering_context2d_font_stretch_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_fontStretch"

///|
fn offscreen_canvas_rendering_context2d_set_font_stretch_ffi(
  obj : JsValue,
  font_stretch : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_fontStretch"

///|
fn offscreen_canvas_rendering_context2d_font_variant_caps_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_fontVariantCaps"

///|
fn offscreen_canvas_rendering_context2d_set_font_variant_caps_ffi(
  obj : JsValue,
  font_variant_caps : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_fontVariantCaps"

///|
fn offscreen_canvas_rendering_context2d_text_rendering_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_textRendering"

///|
fn offscreen_canvas_rendering_context2d_set_text_rendering_ffi(
  obj : JsValue,
  text_rendering : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_textRendering"

///|
fn offscreen_canvas_rendering_context2d_word_spacing_ffi(
  obj : JsValue,
) -> JsValue = "webapi_OffscreenCanvasRenderingContext2D" "get_wordSpacing"

///|
fn offscreen_canvas_rendering_context2d_set_word_spacing_ffi(
  obj : JsValue,
  word_spacing : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "set_wordSpacing"

///|
fn offscreen_canvas_rendering_context2d_close_path_ffi(obj : JsValue) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "closePath"

///|
fn offscreen_canvas_rendering_context2d_move_to_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "moveTo"

///|
fn offscreen_canvas_rendering_context2d_line_to_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "lineTo"

///|
fn offscreen_canvas_rendering_context2d_quadratic_curve_to_ffi(
  obj : JsValue,
  cpx : JsValue,
  cpy : JsValue,
  x : JsValue,
  y : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "quadraticCurveTo"

///|
fn offscreen_canvas_rendering_context2d_bezier_curve_to_ffi(
  obj : JsValue,
  cp1x : JsValue,
  cp1y : JsValue,
  cp2x : JsValue,
  cp2y : JsValue,
  x : JsValue,
  y : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "bezierCurveTo"

///|
fn offscreen_canvas_rendering_context2d_arc_to_ffi(
  obj : JsValue,
  x1 : JsValue,
  y1 : JsValue,
  x2 : JsValue,
  y2 : JsValue,
  radius : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "arcTo"

///|
fn offscreen_canvas_rendering_context2d_rect_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  w : JsValue,
  h : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "rect"

///|
fn offscreen_canvas_rendering_context2d_round_rect_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  w : JsValue,
  h : JsValue,
  radii : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "roundRect"

///|
fn offscreen_canvas_rendering_context2d_arc_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  radius : JsValue,
  start_angle : JsValue,
  end_angle : JsValue,
  counterclockwise : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "arc"

///|
fn offscreen_canvas_rendering_context2d_ellipse_ffi(
  obj : JsValue,
  x : JsValue,
  y : JsValue,
  radius_x : JsValue,
  radius_y : JsValue,
  rotation : JsValue,
  start_angle : JsValue,
  end_angle : JsValue,
  counterclockwise : JsValue,
) -> Unit = "webapi_OffscreenCanvasRenderingContext2D" "ellipse"
