fn resize_observer_entry_target_ffi(obj: JsValue) -> Element = "webapi_ResizeObserverEntry" "get_target"

fn resize_observer_entry_content_rect_ffi(obj: JsValue) -> DOMRectReadOnly = "webapi_ResizeObserverEntry" "get_contentRect"

fn resize_observer_entry_border_box_size_ffi(obj: JsValue) -> JsValue = "webapi_ResizeObserverEntry" "get_borderBoxSize"

fn resize_observer_entry_content_box_size_ffi(obj: JsValue) -> JsValue = "webapi_ResizeObserverEntry" "get_contentBoxSize"

fn resize_observer_entry_device_pixel_content_box_size_ffi(obj: JsValue) -> JsValue = "webapi_ResizeObserverEntry" "get_devicePixelContentBoxSize"