///|
fn screen_avail_width_ffi(obj : JsValue) -> JsValue = "webapi_Screen" "get_availWidth"

///|
fn screen_avail_height_ffi(obj : JsValue) -> JsValue = "webapi_Screen" "get_availHeight"

///|
fn screen_width_ffi(obj : JsValue) -> JsValue = "webapi_Screen" "get_width"

///|
fn screen_height_ffi(obj : JsValue) -> JsValue = "webapi_Screen" "get_height"

///|
fn screen_color_depth_ffi(obj : JsValue) -> JsValue = "webapi_Screen" "get_colorDepth"

///|
fn screen_pixel_depth_ffi(obj : JsValue) -> JsValue = "webapi_Screen" "get_pixelDepth"
