///|
extern "js" fn svg_rect_element_x_ffi(obj : JsValue) -> JsValue = "(obj) => obj.x"

///|
extern "js" fn svg_rect_element_y_ffi(obj : JsValue) -> JsValue = "(obj) => obj.y"

///|
extern "js" fn svg_rect_element_width_ffi(obj : JsValue) -> JsValue = "(obj) => obj.width"

///|
extern "js" fn svg_rect_element_height_ffi(obj : JsValue) -> JsValue = "(obj) => obj.height"

///|
extern "js" fn svg_rect_element_rx_ffi(obj : JsValue) -> JsValue = "(obj) => obj.rx"

///|
extern "js" fn svg_rect_element_ry_ffi(obj : JsValue) -> JsValue = "(obj) => obj.ry"
