fn svg_linear_gradient_element_x1_ffi(obj: JsValue) -> JsValue = "webapi_SVGLinearGradientElement" "get_x1"

fn svg_linear_gradient_element_y1_ffi(obj: JsValue) -> JsValue = "webapi_SVGLinearGradientElement" "get_y1"

fn svg_linear_gradient_element_x2_ffi(obj: JsValue) -> JsValue = "webapi_SVGLinearGradientElement" "get_x2"

fn svg_linear_gradient_element_y2_ffi(obj: JsValue) -> JsValue = "webapi_SVGLinearGradientElement" "get_y2"