fn svg_rect_element_x_ffi(obj: JsValue) -> JsValue = "webapi_SVGRectElement" "get_x"

fn svg_rect_element_y_ffi(obj: JsValue) -> JsValue = "webapi_SVGRectElement" "get_y"

fn svg_rect_element_width_ffi(obj: JsValue) -> JsValue = "webapi_SVGRectElement" "get_width"

fn svg_rect_element_height_ffi(obj: JsValue) -> JsValue = "webapi_SVGRectElement" "get_height"

fn svg_rect_element_rx_ffi(obj: JsValue) -> JsValue = "webapi_SVGRectElement" "get_rx"

fn svg_rect_element_ry_ffi(obj: JsValue) -> JsValue = "webapi_SVGRectElement" "get_ry"