fn svga_element_target_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_target"

fn svga_element_download_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_download"

fn svga_element_set_download_ffi(obj: JsValue, download: JsValue) -> Unit = "webapi_SVGAElement" "set_download"

fn svga_element_ping_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_ping"

fn svga_element_set_ping_ffi(obj: JsValue, ping: JsValue) -> Unit = "webapi_SVGAElement" "set_ping"

fn svga_element_rel_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_rel"

fn svga_element_set_rel_ffi(obj: JsValue, rel: JsValue) -> Unit = "webapi_SVGAElement" "set_rel"

fn svga_element_rel_list_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_relList"

fn svga_element_hreflang_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_hreflang"

fn svga_element_set_hreflang_ffi(obj: JsValue, hreflang: JsValue) -> Unit = "webapi_SVGAElement" "set_hreflang"

fn svga_element_type_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_type"

fn svga_element_set_type_ffi(obj: JsValue, type_: JsValue) -> Unit = "webapi_SVGAElement" "set_type"

fn svga_element_referrer_policy_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_referrerPolicy"

fn svga_element_set_referrer_policy_ffi(obj: JsValue, referrer_policy: JsValue) -> Unit = "webapi_SVGAElement" "set_referrerPolicy"

fn svga_element_origin_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_origin"

fn svga_element_protocol_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_protocol"

fn svga_element_set_protocol_ffi(obj: JsValue, protocol: JsValue) -> Unit = "webapi_SVGAElement" "set_protocol"

fn svga_element_username_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_username"

fn svga_element_set_username_ffi(obj: JsValue, username: JsValue) -> Unit = "webapi_SVGAElement" "set_username"

fn svga_element_password_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_password"

fn svga_element_set_password_ffi(obj: JsValue, password: JsValue) -> Unit = "webapi_SVGAElement" "set_password"

fn svga_element_host_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_host"

fn svga_element_set_host_ffi(obj: JsValue, host: JsValue) -> Unit = "webapi_SVGAElement" "set_host"

fn svga_element_hostname_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_hostname"

fn svga_element_set_hostname_ffi(obj: JsValue, hostname: JsValue) -> Unit = "webapi_SVGAElement" "set_hostname"

fn svga_element_port_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_port"

fn svga_element_set_port_ffi(obj: JsValue, port: JsValue) -> Unit = "webapi_SVGAElement" "set_port"

fn svga_element_pathname_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_pathname"

fn svga_element_set_pathname_ffi(obj: JsValue, pathname: JsValue) -> Unit = "webapi_SVGAElement" "set_pathname"

fn svga_element_search_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_search"

fn svga_element_set_search_ffi(obj: JsValue, search: JsValue) -> Unit = "webapi_SVGAElement" "set_search"

fn svga_element_hash_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_hash"

fn svga_element_set_hash_ffi(obj: JsValue, hash: JsValue) -> Unit = "webapi_SVGAElement" "set_hash"

fn svga_element_href_ffi(obj: JsValue) -> JsValue = "webapi_SVGAElement" "get_href"