fn visibility_state_entry_name_ffi(obj: JsValue) -> JsValue = "webapi_VisibilityStateEntry" "get_name"

fn visibility_state_entry_entry_type_ffi(obj: JsValue) -> JsValue = "webapi_VisibilityStateEntry" "get_entryType"

fn visibility_state_entry_start_time_ffi(obj: JsValue) -> JsValue = "webapi_VisibilityStateEntry" "get_startTime"

fn visibility_state_entry_duration_ffi(obj: JsValue) -> JsValue = "webapi_VisibilityStateEntry" "get_duration"