/**
 * Auto-generated JavaScript runtime for MoonBit DOM bindings
 * Do not edit manually
 */

export const wasmImportObject = {
  "moonbit:ffi": {
    make_closure: (funcref, closure) => funcref.bind(null, closure)
  },

  JsValue: {
    undefined: () => undefined,
    null: () => null,
    isNull: (value) => value === null || value === undefined
  },

  JsNull: {
    null: () => null
  },

  JsArray: {
    empty: () => [],
    push: (arr, value) => arr.push(value)
  },

  JsPromise: {
    await: (promise) => promise,
    resolve: (value) => Promise.resolve(value),
    reject: (error) => Promise.reject(error)
  },

  webapi_Dictionary: {
    empty: () => ({})
  },

  webapi_Globals: {
    document: () => document,
    window: () => window,
    console: () => console,
    navigator: () => navigator
  },

  webapi_CustomElementConstructor: {
    new: (f) => f
  },

  webapi_NavigationInterceptHandler: {
    new: (f) => f
  },

  webapi_NavigationPrecommitHandler: {
    new: (f) => f
  },

  webapi_EventHandlerNonNull: {
    new: (f) => f
  },

  webapi_OnErrorEventHandlerNonNull: {
    new: (f) => f
  },

  webapi_OnBeforeUnloadEventHandlerNonNull: {
    new: (f) => f
  },

  webapi_FrameRequestCallback: {
    new: (f) => f
  },

  webapi_EventListener: {
    new: (f) => f
  },

  webapi_NodeFilter: {
    new: (f) => f
  },

  webapi_XPathNSResolver: {
    new: (f) => f
  },

  webapi_Document: {
    new: () => new Document(),
    get_rootElement: (obj) => obj.rootElement,
    get_implementation: (obj) => obj.implementation,
    get_URL: (obj) => obj.URL,
    get_documentURI: (obj) => obj.documentURI,
    get_compatMode: (obj) => obj.compatMode,
    get_characterSet: (obj) => obj.characterSet,
    get_charset: (obj) => obj.charset,
    get_inputEncoding: (obj) => obj.inputEncoding,
    get_contentType: (obj) => obj.contentType,
    get_doctype: (obj) => obj.doctype,
    get_documentElement: (obj) => obj.documentElement,
    get_location: (obj) => obj.location,
    get_domain: (obj) => obj.domain,
    set_domain: (obj, value) => { obj.domain = value; },
    get_referrer: (obj) => obj.referrer,
    get_cookie: (obj) => obj.cookie,
    set_cookie: (obj, value) => { obj.cookie = value; },
    get_lastModified: (obj) => obj.lastModified,
    get_readyState: (obj) => obj.readyState,
    get_title: (obj) => obj.title,
    set_title: (obj, value) => { obj.title = value; },
    get_dir: (obj) => obj.dir,
    set_dir: (obj, value) => { obj.dir = value; },
    get_body: (obj) => obj.body,
    set_body: (obj, value) => { obj.body = value; },
    get_head: (obj) => obj.head,
    get_images: (obj) => obj.images,
    get_embeds: (obj) => obj.embeds,
    get_plugins: (obj) => obj.plugins,
    get_links: (obj) => obj.links,
    get_forms: (obj) => obj.forms,
    get_scripts: (obj) => obj.scripts,
    get_currentScript: (obj) => obj.currentScript,
    get_defaultView: (obj) => obj.defaultView,
    get_designMode: (obj) => obj.designMode,
    set_designMode: (obj, value) => { obj.designMode = value; },
    get_hidden: (obj) => obj.hidden,
    get_visibilityState: (obj) => obj.visibilityState,
    get_onreadystatechange: (obj) => obj.onreadystatechange,
    set_onreadystatechange: (obj, value) => { obj.onreadystatechange = value; },
    get_onvisibilitychange: (obj) => obj.onvisibilitychange,
    set_onvisibilitychange: (obj, value) => { obj.onvisibilitychange = value; },
    get_fgColor: (obj) => obj.fgColor,
    set_fgColor: (obj, value) => { obj.fgColor = value; },
    get_linkColor: (obj) => obj.linkColor,
    set_linkColor: (obj, value) => { obj.linkColor = value; },
    get_vlinkColor: (obj) => obj.vlinkColor,
    set_vlinkColor: (obj, value) => { obj.vlinkColor = value; },
    get_alinkColor: (obj) => obj.alinkColor,
    set_alinkColor: (obj, value) => { obj.alinkColor = value; },
    get_bgColor: (obj) => obj.bgColor,
    set_bgColor: (obj, value) => { obj.bgColor = value; },
    get_anchors: (obj) => obj.anchors,
    get_applets: (obj) => obj.applets,
    get_all: (obj) => obj.all,
    get_scrollingElement: (obj) => obj.scrollingElement,
    getElementsByTagName: (obj, qualified_name) => obj.getElementsByTagName(qualified_name),
    getElementsByTagNameNS: (obj, namespace, local_name) => obj.getElementsByTagNameNS(namespace, local_name),
    getElementsByClassName: (obj, class_names) => obj.getElementsByClassName(class_names),
    createElement: (obj, local_name, options) => obj.createElement(local_name, options),
    createElementNS: (obj, namespace, qualified_name, options) => obj.createElementNS(namespace, qualified_name, options),
    createDocumentFragment: (obj) => obj.createDocumentFragment(),
    createTextNode: (obj, data) => obj.createTextNode(data),
    createCDATASection: (obj, data) => obj.createCDATASection(data),
    createComment: (obj, data) => obj.createComment(data),
    createProcessingInstruction: (obj, target, data) => obj.createProcessingInstruction(target, data),
    importNode: (obj, node, options) => obj.importNode(node, options),
    adoptNode: (obj, node) => obj.adoptNode(node),
    createAttribute: (obj, local_name) => obj.createAttribute(local_name),
    createAttributeNS: (obj, namespace, qualified_name) => obj.createAttributeNS(namespace, qualified_name),
    createEvent: (obj, interface) => obj.createEvent(interface),
    createRange: (obj) => obj.createRange(),
    createNodeIterator: (obj, root, what_to_show, filter) => obj.createNodeIterator(root, what_to_show, filter),
    createTreeWalker: (obj, root, what_to_show, filter) => obj.createTreeWalker(root, what_to_show, filter),
    parseHTMLUnsafe: (html) => parseHTMLUnsafe(html),
    getElementsByName: (obj, element_name) => obj.getElementsByName(element_name),
    open: (obj, unused1, unused2) => obj.open(unused1, unused2),
    open: (obj, url, name, features) => obj.open(url, name, features),
    close: (obj) => obj.close(),
    write: (obj, text) => obj.write(text),
    writeln: (obj, text) => obj.writeln(text),
    hasFocus: (obj) => obj.hasFocus(),
    execCommand: (obj, command_id, show_ui, value) => obj.execCommand(command_id, show_ui, value),
    queryCommandEnabled: (obj, command_id) => obj.queryCommandEnabled(command_id),
    queryCommandIndeterm: (obj, command_id) => obj.queryCommandIndeterm(command_id),
    queryCommandState: (obj, command_id) => obj.queryCommandState(command_id),
    queryCommandSupported: (obj, command_id) => obj.queryCommandSupported(command_id),
    queryCommandValue: (obj, command_id) => obj.queryCommandValue(command_id),
    clear: (obj) => obj.clear(),
    captureEvents: (obj) => obj.captureEvents(),
    releaseEvents: (obj) => obj.releaseEvents(),
    elementFromPoint: (obj, x, y) => obj.elementFromPoint(x, y),
    elementsFromPoint: (obj, x, y) => obj.elementsFromPoint(x, y),
    caretPositionFromPoint: (obj, x, y, options) => obj.caretPositionFromPoint(x, y, options)
  },

  webapi_Event: {
    new: (type_, event_init_dict) => new Event(type_, event_init_dict),
    get_type: (obj) => obj.type,
    get_target: (obj) => obj.target,
    get_srcElement: (obj) => obj.srcElement,
    get_currentTarget: (obj) => obj.currentTarget,
    get_eventPhase: (obj) => obj.eventPhase,
    get_cancelBubble: (obj) => obj.cancelBubble,
    set_cancelBubble: (obj, value) => { obj.cancelBubble = value; },
    get_bubbles: (obj) => obj.bubbles,
    get_cancelable: (obj) => obj.cancelable,
    get_returnValue: (obj) => obj.returnValue,
    set_returnValue: (obj, value) => { obj.returnValue = value; },
    get_defaultPrevented: (obj) => obj.defaultPrevented,
    get_composed: (obj) => obj.composed,
    get_isTrusted: (obj) => obj.isTrusted,
    get_timeStamp: (obj) => obj.timeStamp,
    composedPath: (obj) => obj.composedPath(),
    stopPropagation: (obj) => obj.stopPropagation(),
    stopImmediatePropagation: (obj) => obj.stopImmediatePropagation(),
    preventDefault: (obj) => obj.preventDefault(),
    initEvent: (obj, type_, bubbles, cancelable) => obj.initEvent(type_, bubbles, cancelable)
  },

  webapi_Window: {
    get_event: (obj) => obj.event,
    get_window: (obj) => obj.window,
    get_self: (obj) => obj.self,
    get_document: (obj) => obj.document,
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_location: (obj) => obj.location,
    get_history: (obj) => obj.history,
    get_navigation: (obj) => obj.navigation,
    get_customElements: (obj) => obj.customElements,
    get_locationbar: (obj) => obj.locationbar,
    get_menubar: (obj) => obj.menubar,
    get_personalbar: (obj) => obj.personalbar,
    get_scrollbars: (obj) => obj.scrollbars,
    get_statusbar: (obj) => obj.statusbar,
    get_toolbar: (obj) => obj.toolbar,
    get_status: (obj) => obj.status,
    set_status: (obj, value) => { obj.status = value; },
    get_closed: (obj) => obj.closed,
    get_frames: (obj) => obj.frames,
    get_length: (obj) => obj.length,
    get_top: (obj) => obj.top,
    get_opener: (obj) => obj.opener,
    set_opener: (obj, value) => { obj.opener = value; },
    get_parent: (obj) => obj.parent,
    get_frameElement: (obj) => obj.frameElement,
    get_navigator: (obj) => obj.navigator,
    get_clientInformation: (obj) => obj.clientInformation,
    get_originAgentCluster: (obj) => obj.originAgentCluster,
    get_external: (obj) => obj.external,
    get_screen: (obj) => obj.screen,
    get_visualViewport: (obj) => obj.visualViewport,
    get_innerWidth: (obj) => obj.innerWidth,
    get_innerHeight: (obj) => obj.innerHeight,
    get_scrollX: (obj) => obj.scrollX,
    get_pageXOffset: (obj) => obj.pageXOffset,
    get_scrollY: (obj) => obj.scrollY,
    get_pageYOffset: (obj) => obj.pageYOffset,
    get_screenX: (obj) => obj.screenX,
    get_screenLeft: (obj) => obj.screenLeft,
    get_screenY: (obj) => obj.screenY,
    get_screenTop: (obj) => obj.screenTop,
    get_outerWidth: (obj) => obj.outerWidth,
    get_outerHeight: (obj) => obj.outerHeight,
    get_devicePixelRatio: (obj) => obj.devicePixelRatio,
    close: (obj) => obj.close(),
    stop: (obj) => obj.stop(),
    focus: (obj) => obj.focus(),
    blur: (obj) => obj.blur(),
    open: (obj, url, target, features) => obj.open(url, target, features),
    alert: (obj) => obj.alert(),
    alert: (obj, message) => obj.alert(message),
    confirm: (obj, message) => obj.confirm(message),
    prompt: (obj, message, default) => obj.prompt(message, default),
    print: (obj) => obj.print(),
    postMessage: (obj, message, target_origin, transfer) => obj.postMessage(message, target_origin, transfer),
    postMessage: (obj, message, options) => obj.postMessage(message, options),
    captureEvents: (obj) => obj.captureEvents(),
    releaseEvents: (obj) => obj.releaseEvents(),
    getComputedStyle: (obj, elt, pseudo_elt) => obj.getComputedStyle(elt, pseudo_elt),
    matchMedia: (obj, query) => obj.matchMedia(query),
    moveTo: (obj, x, y) => obj.moveTo(x, y),
    moveBy: (obj, x, y) => obj.moveBy(x, y),
    resizeTo: (obj, width, height) => obj.resizeTo(width, height),
    resizeBy: (obj, x, y) => obj.resizeBy(x, y),
    scroll: (obj, options) => obj.scroll(options),
    scroll: (obj, x, y) => obj.scroll(x, y),
    scrollTo: (obj, options) => obj.scrollTo(options),
    scrollTo: (obj, x, y) => obj.scrollTo(x, y),
    scrollBy: (obj, options) => obj.scrollBy(options),
    scrollBy: (obj, x, y) => obj.scrollBy(x, y)
  },

  webapi_CustomEvent: {
    new: (type_, event_init_dict) => new CustomEvent(type_, event_init_dict),
    get_detail: (obj) => obj.detail,
    initCustomEvent: (obj, type_, bubbles, cancelable, detail) => obj.initCustomEvent(type_, bubbles, cancelable, detail)
  },

  webapi_EventTarget: {
    new: () => new EventTarget(),
    addEventListener: (obj, type_, callback, options) => obj.addEventListener(type_, callback, options),
    removeEventListener: (obj, type_, callback, options) => obj.removeEventListener(type_, callback, options),
    dispatchEvent: (obj, event) => obj.dispatchEvent(event)
  },

  webapi_AbortController: {
    new: () => new AbortController(),
    get_signal: (obj) => obj.signal,
    abort: (obj, reason) => obj.abort(reason)
  },

  webapi_AbortSignal: {
    get_aborted: (obj) => obj.aborted,
    get_reason: (obj) => obj.reason,
    get_onabort: (obj) => obj.onabort,
    set_onabort: (obj, value) => { obj.onabort = value; },
    abort: (reason) => abort(reason),
    timeout: (milliseconds) => timeout(milliseconds),
    _any: (signals) => _any(signals),
    throwIfAborted: (obj) => obj.throwIfAborted()
  },

  webapi_NodeList: {
    get_length: (obj) => obj.length
  },

  webapi_HTMLCollection: {
    get_length: (obj) => obj.length
  },

  webapi_MutationObserver: {
    new: (callback) => new MutationObserver(callback),
    observe: (obj, target, options) => obj.observe(target, options),
    disconnect: (obj) => obj.disconnect(),
    takeRecords: (obj) => obj.takeRecords()
  },

  webapi_MutationRecord: {
    get_type: (obj) => obj.type,
    get_target: (obj) => obj.target,
    get_addedNodes: (obj) => obj.addedNodes,
    get_removedNodes: (obj) => obj.removedNodes,
    get_previousSibling: (obj) => obj.previousSibling,
    get_nextSibling: (obj) => obj.nextSibling,
    get_attributeName: (obj) => obj.attributeName,
    get_attributeNamespace: (obj) => obj.attributeNamespace,
    get_oldValue: (obj) => obj.oldValue
  },

  webapi_Node: {
    get_nodeType: (obj) => obj.nodeType,
    get_nodeName: (obj) => obj.nodeName,
    get_baseURI: (obj) => obj.baseURI,
    get_isConnected: (obj) => obj.isConnected,
    get_ownerDocument: (obj) => obj.ownerDocument,
    get_parentNode: (obj) => obj.parentNode,
    get_parentElement: (obj) => obj.parentElement,
    get_childNodes: (obj) => obj.childNodes,
    get_firstChild: (obj) => obj.firstChild,
    get_lastChild: (obj) => obj.lastChild,
    get_previousSibling: (obj) => obj.previousSibling,
    get_nextSibling: (obj) => obj.nextSibling,
    get_nodeValue: (obj) => obj.nodeValue,
    set_nodeValue: (obj, value) => { obj.nodeValue = value; },
    get_textContent: (obj) => obj.textContent,
    set_textContent: (obj, value) => { obj.textContent = value; },
    getRootNode: (obj, options) => obj.getRootNode(options),
    hasChildNodes: (obj) => obj.hasChildNodes(),
    normalize: (obj) => obj.normalize(),
    cloneNode: (obj, subtree) => obj.cloneNode(subtree),
    isEqualNode: (obj, other_node) => obj.isEqualNode(other_node),
    isSameNode: (obj, other_node) => obj.isSameNode(other_node),
    compareDocumentPosition: (obj, other) => obj.compareDocumentPosition(other),
    contains: (obj, other) => obj.contains(other),
    lookupPrefix: (obj, namespace) => obj.lookupPrefix(namespace),
    lookupNamespaceURI: (obj, prefix) => obj.lookupNamespaceURI(prefix),
    isDefaultNamespace: (obj, namespace) => obj.isDefaultNamespace(namespace),
    insertBefore: (obj, node, child) => obj.insertBefore(node, child),
    appendChild: (obj, node) => obj.appendChild(node),
    replaceChild: (obj, node, child) => obj.replaceChild(node, child),
    removeChild: (obj, child) => obj.removeChild(child)
  },

  webapi_DOMImplementation: {
    createDocumentType: (obj, name, public_id, system_id) => obj.createDocumentType(name, public_id, system_id),
    createDocument: (obj, namespace, qualified_name, doctype) => obj.createDocument(namespace, qualified_name, doctype),
    createHTMLDocument: (obj, title) => obj.createHTMLDocument(title),
    hasFeature: (obj) => obj.hasFeature()
  },

  webapi_DocumentType: {
    get_name: (obj) => obj.name,
    get_publicId: (obj) => obj.publicId,
    get_systemId: (obj) => obj.systemId
  },

  webapi_DocumentFragment: {
    new: () => new DocumentFragment()
  },

  webapi_ShadowRoot: {
    get_mode: (obj) => obj.mode,
    get_delegatesFocus: (obj) => obj.delegatesFocus,
    get_slotAssignment: (obj) => obj.slotAssignment,
    get_clonable: (obj) => obj.clonable,
    get_serializable: (obj) => obj.serializable,
    get_host: (obj) => obj.host,
    get_onslotchange: (obj) => obj.onslotchange,
    set_onslotchange: (obj, value) => { obj.onslotchange = value; },
    get_innerHTML: (obj) => obj.innerHTML,
    set_innerHTML: (obj, value) => { obj.innerHTML = value; },
    setHTMLUnsafe: (obj, html) => obj.setHTMLUnsafe(html),
    getHTML: (obj, options) => obj.getHTML(options)
  },

  webapi_Element: {
    get_namespaceURI: (obj) => obj.namespaceURI,
    get_prefix: (obj) => obj.prefix,
    get_localName: (obj) => obj.localName,
    get_tagName: (obj) => obj.tagName,
    get_id: (obj) => obj.id,
    set_id: (obj, value) => { obj.id = value; },
    get_className: (obj) => obj.className,
    set_className: (obj, value) => { obj.className = value; },
    get_classList: (obj) => obj.classList,
    get_slot: (obj) => obj.slot,
    set_slot: (obj, value) => { obj.slot = value; },
    get_attributes: (obj) => obj.attributes,
    get_shadowRoot: (obj) => obj.shadowRoot,
    get_customElementRegistry: (obj) => obj.customElementRegistry,
    get_innerHTML: (obj) => obj.innerHTML,
    set_innerHTML: (obj, value) => { obj.innerHTML = value; },
    get_outerHTML: (obj) => obj.outerHTML,
    set_outerHTML: (obj, value) => { obj.outerHTML = value; },
    get_scrollTop: (obj) => obj.scrollTop,
    set_scrollTop: (obj, value) => { obj.scrollTop = value; },
    get_scrollLeft: (obj) => obj.scrollLeft,
    set_scrollLeft: (obj, value) => { obj.scrollLeft = value; },
    get_scrollWidth: (obj) => obj.scrollWidth,
    get_scrollHeight: (obj) => obj.scrollHeight,
    get_clientTop: (obj) => obj.clientTop,
    get_clientLeft: (obj) => obj.clientLeft,
    get_clientWidth: (obj) => obj.clientWidth,
    get_clientHeight: (obj) => obj.clientHeight,
    get_currentCSSZoom: (obj) => obj.currentCSSZoom,
    hasAttributes: (obj) => obj.hasAttributes(),
    getAttributeNames: (obj) => obj.getAttributeNames(),
    getAttribute: (obj, qualified_name) => obj.getAttribute(qualified_name),
    getAttributeNS: (obj, namespace, local_name) => obj.getAttributeNS(namespace, local_name),
    setAttribute: (obj, qualified_name, value) => obj.setAttribute(qualified_name, value),
    setAttributeNS: (obj, namespace, qualified_name, value) => obj.setAttributeNS(namespace, qualified_name, value),
    removeAttribute: (obj, qualified_name) => obj.removeAttribute(qualified_name),
    removeAttributeNS: (obj, namespace, local_name) => obj.removeAttributeNS(namespace, local_name),
    toggleAttribute: (obj, qualified_name, force) => obj.toggleAttribute(qualified_name, force),
    hasAttribute: (obj, qualified_name) => obj.hasAttribute(qualified_name),
    hasAttributeNS: (obj, namespace, local_name) => obj.hasAttributeNS(namespace, local_name),
    getAttributeNode: (obj, qualified_name) => obj.getAttributeNode(qualified_name),
    getAttributeNodeNS: (obj, namespace, local_name) => obj.getAttributeNodeNS(namespace, local_name),
    setAttributeNode: (obj, attr) => obj.setAttributeNode(attr),
    setAttributeNodeNS: (obj, attr) => obj.setAttributeNodeNS(attr),
    removeAttributeNode: (obj, attr) => obj.removeAttributeNode(attr),
    attachShadow: (obj, init) => obj.attachShadow(init),
    closest: (obj, selectors) => obj.closest(selectors),
    matches: (obj, selectors) => obj.matches(selectors),
    webkitMatchesSelector: (obj, selectors) => obj.webkitMatchesSelector(selectors),
    getElementsByTagName: (obj, qualified_name) => obj.getElementsByTagName(qualified_name),
    getElementsByTagNameNS: (obj, namespace, local_name) => obj.getElementsByTagNameNS(namespace, local_name),
    getElementsByClassName: (obj, class_names) => obj.getElementsByClassName(class_names),
    insertAdjacentElement: (obj, where, element) => obj.insertAdjacentElement(where, element),
    insertAdjacentText: (obj, where, data) => obj.insertAdjacentText(where, data),
    setHTMLUnsafe: (obj, html) => obj.setHTMLUnsafe(html),
    getHTML: (obj, options) => obj.getHTML(options),
    insertAdjacentHTML: (obj, position, string) => obj.insertAdjacentHTML(position, string),
    getClientRects: (obj) => obj.getClientRects(),
    getBoundingClientRect: (obj) => obj.getBoundingClientRect(),
    checkVisibility: (obj, options) => obj.checkVisibility(options),
    scrollIntoView: (obj, arg) => obj.scrollIntoView(arg),
    scroll: (obj, options) => obj.scroll(options),
    scroll: (obj, x, y) => obj.scroll(x, y),
    scrollTo: (obj, options) => obj.scrollTo(options),
    scrollTo: (obj, x, y) => obj.scrollTo(x, y),
    scrollBy: (obj, options) => obj.scrollBy(options),
    scrollBy: (obj, x, y) => obj.scrollBy(x, y)
  },

  webapi_NamedNodeMap: {
    get_length: (obj) => obj.length,
    getNamedItemNS: (obj, namespace, local_name) => obj.getNamedItemNS(namespace, local_name),
    setNamedItem: (obj, attr) => obj.setNamedItem(attr),
    setNamedItemNS: (obj, attr) => obj.setNamedItemNS(attr),
    removeNamedItem: (obj, qualified_name) => obj.removeNamedItem(qualified_name),
    removeNamedItemNS: (obj, namespace, local_name) => obj.removeNamedItemNS(namespace, local_name)
  },

  webapi_Attr: {
    get_namespaceURI: (obj) => obj.namespaceURI,
    get_prefix: (obj) => obj.prefix,
    get_localName: (obj) => obj.localName,
    get_name: (obj) => obj.name,
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_ownerElement: (obj) => obj.ownerElement,
    get_specified: (obj) => obj.specified
  },

  webapi_CharacterData: {
    get_data: (obj) => obj.data,
    set_data: (obj, value) => { obj.data = value; },
    get_length: (obj) => obj.length,
    substringData: (obj, offset, count) => obj.substringData(offset, count),
    appendData: (obj, data) => obj.appendData(data),
    insertData: (obj, offset, data) => obj.insertData(offset, data),
    deleteData: (obj, offset, count) => obj.deleteData(offset, count),
    replaceData: (obj, offset, count, data) => obj.replaceData(offset, count, data)
  },

  webapi_Text: {
    new: (data) => new Text(data),
    get_wholeText: (obj) => obj.wholeText,
    splitText: (obj, offset) => obj.splitText(offset)
  },

  webapi_CDATASection: {
  },

  webapi_ProcessingInstruction: {
    get_target: (obj) => obj.target
  },

  webapi_Comment: {
    new: (data) => new Comment(data)
  },

  webapi_AbstractRange: {
    get_startContainer: (obj) => obj.startContainer,
    get_startOffset: (obj) => obj.startOffset,
    get_endContainer: (obj) => obj.endContainer,
    get_endOffset: (obj) => obj.endOffset,
    get_collapsed: (obj) => obj.collapsed
  },

  webapi_StaticRange: {
    new: (init) => new StaticRange(init)
  },

  webapi_Range: {
    new: () => new Range(),
    get_commonAncestorContainer: (obj) => obj.commonAncestorContainer,
    setStart: (obj, node, offset) => obj.setStart(node, offset),
    setEnd: (obj, node, offset) => obj.setEnd(node, offset),
    setStartBefore: (obj, node) => obj.setStartBefore(node),
    setStartAfter: (obj, node) => obj.setStartAfter(node),
    setEndBefore: (obj, node) => obj.setEndBefore(node),
    setEndAfter: (obj, node) => obj.setEndAfter(node),
    collapse: (obj, to_start) => obj.collapse(to_start),
    selectNode: (obj, node) => obj.selectNode(node),
    selectNodeContents: (obj, node) => obj.selectNodeContents(node),
    compareBoundaryPoints: (obj, how, source_range) => obj.compareBoundaryPoints(how, source_range),
    deleteContents: (obj) => obj.deleteContents(),
    extractContents: (obj) => obj.extractContents(),
    cloneContents: (obj) => obj.cloneContents(),
    insertNode: (obj, node) => obj.insertNode(node),
    surroundContents: (obj, new_parent) => obj.surroundContents(new_parent),
    cloneRange: (obj) => obj.cloneRange(),
    detach: (obj) => obj.detach(),
    isPointInRange: (obj, node, offset) => obj.isPointInRange(node, offset),
    comparePoint: (obj, node, offset) => obj.comparePoint(node, offset),
    intersectsNode: (obj, node) => obj.intersectsNode(node),
    createContextualFragment: (obj, string) => obj.createContextualFragment(string),
    getClientRects: (obj) => obj.getClientRects(),
    getBoundingClientRect: (obj) => obj.getBoundingClientRect()
  },

  webapi_TreeWalker: {
    get_root: (obj) => obj.root,
    get_whatToShow: (obj) => obj.whatToShow,
    get_filter: (obj) => obj.filter,
    get_currentNode: (obj) => obj.currentNode,
    set_currentNode: (obj, value) => { obj.currentNode = value; },
    parentNode: (obj) => obj.parentNode(),
    firstChild: (obj) => obj.firstChild(),
    lastChild: (obj) => obj.lastChild(),
    previousSibling: (obj) => obj.previousSibling(),
    nextSibling: (obj) => obj.nextSibling(),
    previousNode: (obj) => obj.previousNode(),
    nextNode: (obj) => obj.nextNode()
  },

  webapi_DOMTokenList: {
    get_length: (obj) => obj.length,
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    contains: (obj, token) => obj.contains(token),
    add: (obj, tokens) => obj.add(tokens),
    remove: (obj, tokens) => obj.remove(tokens),
    toggle: (obj, token, force) => obj.toggle(token, force),
    replace: (obj, token, new_token) => obj.replace(token, new_token),
    supports: (obj, token) => obj.supports(token)
  },

  webapi_HTMLOptionsCollection: {
    get_length: (obj) => obj.length,
    set_length: (obj, value) => { obj.length = value; },
    get_selectedIndex: (obj) => obj.selectedIndex,
    set_selectedIndex: (obj, value) => { obj.selectedIndex = value; },
    add: (obj, element, before) => obj.add(element, before),
    remove: (obj, index) => obj.remove(index)
  },

  webapi_HTMLElement: {
    new: () => new HTMLElement(),
    get_title: (obj) => obj.title,
    set_title: (obj, value) => { obj.title = value; },
    get_lang: (obj) => obj.lang,
    set_lang: (obj, value) => { obj.lang = value; },
    get_translate: (obj) => obj.translate,
    set_translate: (obj, value) => { obj.translate = value; },
    get_dir: (obj) => obj.dir,
    set_dir: (obj, value) => { obj.dir = value; },
    get_hidden: (obj) => obj.hidden,
    set_hidden: (obj, value) => { obj.hidden = value; },
    get_inert: (obj) => obj.inert,
    set_inert: (obj, value) => { obj.inert = value; },
    get_accessKey: (obj) => obj.accessKey,
    set_accessKey: (obj, value) => { obj.accessKey = value; },
    get_accessKeyLabel: (obj) => obj.accessKeyLabel,
    get_draggable: (obj) => obj.draggable,
    set_draggable: (obj, value) => { obj.draggable = value; },
    get_spellcheck: (obj) => obj.spellcheck,
    set_spellcheck: (obj, value) => { obj.spellcheck = value; },
    get_writingSuggestions: (obj) => obj.writingSuggestions,
    set_writingSuggestions: (obj, value) => { obj.writingSuggestions = value; },
    get_autocapitalize: (obj) => obj.autocapitalize,
    set_autocapitalize: (obj, value) => { obj.autocapitalize = value; },
    get_autocorrect: (obj) => obj.autocorrect,
    set_autocorrect: (obj, value) => { obj.autocorrect = value; },
    get_innerText: (obj) => obj.innerText,
    set_innerText: (obj, value) => { obj.innerText = value; },
    get_outerText: (obj) => obj.outerText,
    set_outerText: (obj, value) => { obj.outerText = value; },
    get_popover: (obj) => obj.popover,
    set_popover: (obj, value) => { obj.popover = value; },
    get_headingOffset: (obj) => obj.headingOffset,
    set_headingOffset: (obj, value) => { obj.headingOffset = value; },
    get_headingReset: (obj) => obj.headingReset,
    set_headingReset: (obj, value) => { obj.headingReset = value; },
    get_scrollParent: (obj) => obj.scrollParent,
    get_offsetParent: (obj) => obj.offsetParent,
    get_offsetTop: (obj) => obj.offsetTop,
    get_offsetLeft: (obj) => obj.offsetLeft,
    get_offsetWidth: (obj) => obj.offsetWidth,
    get_offsetHeight: (obj) => obj.offsetHeight,
    click: (obj) => obj.click(),
    attachInternals: (obj) => obj.attachInternals(),
    showPopover: (obj, options) => obj.showPopover(options),
    hidePopover: (obj) => obj.hidePopover(),
    togglePopover: (obj, options) => obj.togglePopover(options)
  },

  webapi_HTMLUnknownElement: {
  },

  webapi_HTMLHtmlElement: {
    new: () => new HTMLHtmlElement(),
    get_version: (obj) => obj.version,
    set_version: (obj, value) => { obj.version = value; }
  },

  webapi_HTMLHeadElement: {
    new: () => new HTMLHeadElement()
  },

  webapi_HTMLTitleElement: {
    new: () => new HTMLTitleElement(),
    get_text: (obj) => obj.text,
    set_text: (obj, value) => { obj.text = value; }
  },

  webapi_HTMLBaseElement: {
    new: () => new HTMLBaseElement(),
    get_href: (obj) => obj.href,
    set_href: (obj, value) => { obj.href = value; },
    get_target: (obj) => obj.target,
    set_target: (obj, value) => { obj.target = value; }
  },

  webapi_HTMLLinkElement: {
    new: () => new HTMLLinkElement(),
    get_href: (obj) => obj.href,
    set_href: (obj, value) => { obj.href = value; },
    get_crossOrigin: (obj) => obj.crossOrigin,
    set_crossOrigin: (obj, value) => { obj.crossOrigin = value; },
    get_rel: (obj) => obj.rel,
    set_rel: (obj, value) => { obj.rel = value; },
    get_as: (obj) => obj.as,
    set_as: (obj, value) => { obj.as = value; },
    get_relList: (obj) => obj.relList,
    get_media: (obj) => obj.media,
    set_media: (obj, value) => { obj.media = value; },
    get_integrity: (obj) => obj.integrity,
    set_integrity: (obj, value) => { obj.integrity = value; },
    get_hreflang: (obj) => obj.hreflang,
    set_hreflang: (obj, value) => { obj.hreflang = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_sizes: (obj) => obj.sizes,
    get_imageSrcset: (obj) => obj.imageSrcset,
    set_imageSrcset: (obj, value) => { obj.imageSrcset = value; },
    get_imageSizes: (obj) => obj.imageSizes,
    set_imageSizes: (obj, value) => { obj.imageSizes = value; },
    get_referrerPolicy: (obj) => obj.referrerPolicy,
    set_referrerPolicy: (obj, value) => { obj.referrerPolicy = value; },
    get_blocking: (obj) => obj.blocking,
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_fetchPriority: (obj) => obj.fetchPriority,
    set_fetchPriority: (obj, value) => { obj.fetchPriority = value; },
    get_charset: (obj) => obj.charset,
    set_charset: (obj, value) => { obj.charset = value; },
    get_rev: (obj) => obj.rev,
    set_rev: (obj, value) => { obj.rev = value; },
    get_target: (obj) => obj.target,
    set_target: (obj, value) => { obj.target = value; }
  },

  webapi_HTMLMetaElement: {
    new: () => new HTMLMetaElement(),
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_httpEquiv: (obj) => obj.httpEquiv,
    set_httpEquiv: (obj, value) => { obj.httpEquiv = value; },
    get_content: (obj) => obj.content,
    set_content: (obj, value) => { obj.content = value; },
    get_media: (obj) => obj.media,
    set_media: (obj, value) => { obj.media = value; },
    get_scheme: (obj) => obj.scheme,
    set_scheme: (obj, value) => { obj.scheme = value; }
  },

  webapi_HTMLStyleElement: {
    new: () => new HTMLStyleElement(),
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_media: (obj) => obj.media,
    set_media: (obj, value) => { obj.media = value; },
    get_blocking: (obj) => obj.blocking,
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; }
  },

  webapi_HTMLBodyElement: {
    new: () => new HTMLBodyElement(),
    get_text: (obj) => obj.text,
    set_text: (obj, value) => { obj.text = value; },
    get_link: (obj) => obj.link,
    set_link: (obj, value) => { obj.link = value; },
    get_vLink: (obj) => obj.vLink,
    set_vLink: (obj, value) => { obj.vLink = value; },
    get_aLink: (obj) => obj.aLink,
    set_aLink: (obj, value) => { obj.aLink = value; },
    get_bgColor: (obj) => obj.bgColor,
    set_bgColor: (obj, value) => { obj.bgColor = value; },
    get_background: (obj) => obj.background,
    set_background: (obj, value) => { obj.background = value; }
  },

  webapi_HTMLHeadingElement: {
    new: () => new HTMLHeadingElement(),
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; }
  },

  webapi_HTMLParagraphElement: {
    new: () => new HTMLParagraphElement(),
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; }
  },

  webapi_HTMLHRElement: {
    new: () => new HTMLHRElement(),
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_color: (obj) => obj.color,
    set_color: (obj, value) => { obj.color = value; },
    get_noShade: (obj) => obj.noShade,
    set_noShade: (obj, value) => { obj.noShade = value; },
    get_size: (obj) => obj.size,
    set_size: (obj, value) => { obj.size = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; }
  },

  webapi_HTMLPreElement: {
    new: () => new HTMLPreElement(),
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; }
  },

  webapi_HTMLQuoteElement: {
    new: () => new HTMLQuoteElement(),
    get_cite: (obj) => obj.cite,
    set_cite: (obj, value) => { obj.cite = value; }
  },

  webapi_HTMLOListElement: {
    new: () => new HTMLOListElement(),
    get_reversed: (obj) => obj.reversed,
    set_reversed: (obj, value) => { obj.reversed = value; },
    get_start: (obj) => obj.start,
    set_start: (obj, value) => { obj.start = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_compact: (obj) => obj.compact,
    set_compact: (obj, value) => { obj.compact = value; }
  },

  webapi_HTMLUListElement: {
    new: () => new HTMLUListElement(),
    get_compact: (obj) => obj.compact,
    set_compact: (obj, value) => { obj.compact = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; }
  },

  webapi_HTMLMenuElement: {
    new: () => new HTMLMenuElement(),
    get_compact: (obj) => obj.compact,
    set_compact: (obj, value) => { obj.compact = value; }
  },

  webapi_HTMLLIElement: {
    new: () => new HTMLLIElement(),
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; }
  },

  webapi_HTMLDListElement: {
    new: () => new HTMLDListElement(),
    get_compact: (obj) => obj.compact,
    set_compact: (obj, value) => { obj.compact = value; }
  },

  webapi_HTMLDivElement: {
    new: () => new HTMLDivElement(),
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; }
  },

  webapi_HTMLAnchorElement: {
    new: () => new HTMLAnchorElement(),
    get_target: (obj) => obj.target,
    set_target: (obj, value) => { obj.target = value; },
    get_download: (obj) => obj.download,
    set_download: (obj, value) => { obj.download = value; },
    get_ping: (obj) => obj.ping,
    set_ping: (obj, value) => { obj.ping = value; },
    get_rel: (obj) => obj.rel,
    set_rel: (obj, value) => { obj.rel = value; },
    get_relList: (obj) => obj.relList,
    get_hreflang: (obj) => obj.hreflang,
    set_hreflang: (obj, value) => { obj.hreflang = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_text: (obj) => obj.text,
    set_text: (obj, value) => { obj.text = value; },
    get_referrerPolicy: (obj) => obj.referrerPolicy,
    set_referrerPolicy: (obj, value) => { obj.referrerPolicy = value; },
    get_coords: (obj) => obj.coords,
    set_coords: (obj, value) => { obj.coords = value; },
    get_charset: (obj) => obj.charset,
    set_charset: (obj, value) => { obj.charset = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_rev: (obj) => obj.rev,
    set_rev: (obj, value) => { obj.rev = value; },
    get_shape: (obj) => obj.shape,
    set_shape: (obj, value) => { obj.shape = value; }
  },

  webapi_HTMLDataElement: {
    new: () => new HTMLDataElement(),
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; }
  },

  webapi_HTMLTimeElement: {
    new: () => new HTMLTimeElement(),
    get_dateTime: (obj) => obj.dateTime,
    set_dateTime: (obj, value) => { obj.dateTime = value; }
  },

  webapi_HTMLSpanElement: {
    new: () => new HTMLSpanElement()
  },

  webapi_HTMLBRElement: {
    new: () => new HTMLBRElement(),
    get_clear: (obj) => obj.clear,
    set_clear: (obj, value) => { obj.clear = value; }
  },

  webapi_HTMLModElement: {
    new: () => new HTMLModElement(),
    get_cite: (obj) => obj.cite,
    set_cite: (obj, value) => { obj.cite = value; },
    get_dateTime: (obj) => obj.dateTime,
    set_dateTime: (obj, value) => { obj.dateTime = value; }
  },

  webapi_HTMLPictureElement: {
    new: () => new HTMLPictureElement()
  },

  webapi_HTMLSourceElement: {
    new: () => new HTMLSourceElement(),
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_srcset: (obj) => obj.srcset,
    set_srcset: (obj, value) => { obj.srcset = value; },
    get_sizes: (obj) => obj.sizes,
    set_sizes: (obj, value) => { obj.sizes = value; },
    get_media: (obj) => obj.media,
    set_media: (obj, value) => { obj.media = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; }
  },

  webapi_HTMLImageElement: {
    new: () => new HTMLImageElement(),
    get_alt: (obj) => obj.alt,
    set_alt: (obj, value) => { obj.alt = value; },
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_srcset: (obj) => obj.srcset,
    set_srcset: (obj, value) => { obj.srcset = value; },
    get_sizes: (obj) => obj.sizes,
    set_sizes: (obj, value) => { obj.sizes = value; },
    get_crossOrigin: (obj) => obj.crossOrigin,
    set_crossOrigin: (obj, value) => { obj.crossOrigin = value; },
    get_useMap: (obj) => obj.useMap,
    set_useMap: (obj, value) => { obj.useMap = value; },
    get_isMap: (obj) => obj.isMap,
    set_isMap: (obj, value) => { obj.isMap = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_naturalWidth: (obj) => obj.naturalWidth,
    get_naturalHeight: (obj) => obj.naturalHeight,
    get_complete: (obj) => obj.complete,
    get_currentSrc: (obj) => obj.currentSrc,
    get_referrerPolicy: (obj) => obj.referrerPolicy,
    set_referrerPolicy: (obj, value) => { obj.referrerPolicy = value; },
    get_decoding: (obj) => obj.decoding,
    set_decoding: (obj, value) => { obj.decoding = value; },
    get_loading: (obj) => obj.loading,
    set_loading: (obj, value) => { obj.loading = value; },
    get_fetchPriority: (obj) => obj.fetchPriority,
    set_fetchPriority: (obj, value) => { obj.fetchPriority = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_lowsrc: (obj) => obj.lowsrc,
    set_lowsrc: (obj, value) => { obj.lowsrc = value; },
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_hspace: (obj) => obj.hspace,
    set_hspace: (obj, value) => { obj.hspace = value; },
    get_vspace: (obj) => obj.vspace,
    set_vspace: (obj, value) => { obj.vspace = value; },
    get_longDesc: (obj) => obj.longDesc,
    set_longDesc: (obj, value) => { obj.longDesc = value; },
    get_border: (obj) => obj.border,
    set_border: (obj, value) => { obj.border = value; },
    get_x: (obj) => obj.x,
    get_y: (obj) => obj.y,
    decode: (obj) => obj.decode()
  },

  webapi_HTMLIFrameElement: {
    new: () => new HTMLIFrameElement(),
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_srcdoc: (obj) => obj.srcdoc,
    set_srcdoc: (obj, value) => { obj.srcdoc = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_sandbox: (obj) => obj.sandbox,
    get_allow: (obj) => obj.allow,
    set_allow: (obj, value) => { obj.allow = value; },
    get_allowFullscreen: (obj) => obj.allowFullscreen,
    set_allowFullscreen: (obj, value) => { obj.allowFullscreen = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_referrerPolicy: (obj) => obj.referrerPolicy,
    set_referrerPolicy: (obj, value) => { obj.referrerPolicy = value; },
    get_loading: (obj) => obj.loading,
    set_loading: (obj, value) => { obj.loading = value; },
    get_contentDocument: (obj) => obj.contentDocument,
    get_contentWindow: (obj) => obj.contentWindow,
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_scrolling: (obj) => obj.scrolling,
    set_scrolling: (obj, value) => { obj.scrolling = value; },
    get_frameBorder: (obj) => obj.frameBorder,
    set_frameBorder: (obj, value) => { obj.frameBorder = value; },
    get_longDesc: (obj) => obj.longDesc,
    set_longDesc: (obj, value) => { obj.longDesc = value; },
    get_marginHeight: (obj) => obj.marginHeight,
    set_marginHeight: (obj, value) => { obj.marginHeight = value; },
    get_marginWidth: (obj) => obj.marginWidth,
    set_marginWidth: (obj, value) => { obj.marginWidth = value; },
    getSVGDocument: (obj) => obj.getSVGDocument()
  },

  webapi_HTMLEmbedElement: {
    new: () => new HTMLEmbedElement(),
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    getSVGDocument: (obj) => obj.getSVGDocument()
  },

  webapi_HTMLObjectElement: {
    new: () => new HTMLObjectElement(),
    get_data: (obj) => obj.data,
    set_data: (obj, value) => { obj.data = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_form: (obj) => obj.form,
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_contentDocument: (obj) => obj.contentDocument,
    get_contentWindow: (obj) => obj.contentWindow,
    get_willValidate: (obj) => obj.willValidate,
    get_validity: (obj) => obj.validity,
    get_validationMessage: (obj) => obj.validationMessage,
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_archive: (obj) => obj.archive,
    set_archive: (obj, value) => { obj.archive = value; },
    get_code: (obj) => obj.code,
    set_code: (obj, value) => { obj.code = value; },
    get_declare: (obj) => obj.declare,
    set_declare: (obj, value) => { obj.declare = value; },
    get_hspace: (obj) => obj.hspace,
    set_hspace: (obj, value) => { obj.hspace = value; },
    get_standby: (obj) => obj.standby,
    set_standby: (obj, value) => { obj.standby = value; },
    get_vspace: (obj) => obj.vspace,
    set_vspace: (obj, value) => { obj.vspace = value; },
    get_codeBase: (obj) => obj.codeBase,
    set_codeBase: (obj, value) => { obj.codeBase = value; },
    get_codeType: (obj) => obj.codeType,
    set_codeType: (obj, value) => { obj.codeType = value; },
    get_useMap: (obj) => obj.useMap,
    set_useMap: (obj, value) => { obj.useMap = value; },
    get_border: (obj) => obj.border,
    set_border: (obj, value) => { obj.border = value; },
    getSVGDocument: (obj) => obj.getSVGDocument(),
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity(),
    setCustomValidity: (obj, error) => obj.setCustomValidity(error)
  },

  webapi_HTMLVideoElement: {
    new: () => new HTMLVideoElement(),
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_videoWidth: (obj) => obj.videoWidth,
    get_videoHeight: (obj) => obj.videoHeight,
    get_poster: (obj) => obj.poster,
    set_poster: (obj, value) => { obj.poster = value; },
    get_playsInline: (obj) => obj.playsInline,
    set_playsInline: (obj, value) => { obj.playsInline = value; }
  },

  webapi_HTMLAudioElement: {
    new: () => new HTMLAudioElement()
  },

  webapi_HTMLTrackElement: {
    new: () => new HTMLTrackElement(),
    get_kind: (obj) => obj.kind,
    set_kind: (obj, value) => { obj.kind = value; },
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_srclang: (obj) => obj.srclang,
    set_srclang: (obj, value) => { obj.srclang = value; },
    get_label: (obj) => obj.label,
    set_label: (obj, value) => { obj.label = value; },
    get_default: (obj) => obj.default,
    set_default: (obj, value) => { obj.default = value; },
    get_readyState: (obj) => obj.readyState,
    get_track: (obj) => obj.track
  },

  webapi_HTMLMediaElement: {
    get_error: (obj) => obj.error,
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_srcObject: (obj) => obj.srcObject,
    set_srcObject: (obj, value) => { obj.srcObject = value; },
    get_currentSrc: (obj) => obj.currentSrc,
    get_crossOrigin: (obj) => obj.crossOrigin,
    set_crossOrigin: (obj, value) => { obj.crossOrigin = value; },
    get_networkState: (obj) => obj.networkState,
    get_preload: (obj) => obj.preload,
    set_preload: (obj, value) => { obj.preload = value; },
    get_buffered: (obj) => obj.buffered,
    get_readyState: (obj) => obj.readyState,
    get_seeking: (obj) => obj.seeking,
    get_currentTime: (obj) => obj.currentTime,
    set_currentTime: (obj, value) => { obj.currentTime = value; },
    get_duration: (obj) => obj.duration,
    get_paused: (obj) => obj.paused,
    get_defaultPlaybackRate: (obj) => obj.defaultPlaybackRate,
    set_defaultPlaybackRate: (obj, value) => { obj.defaultPlaybackRate = value; },
    get_playbackRate: (obj) => obj.playbackRate,
    set_playbackRate: (obj, value) => { obj.playbackRate = value; },
    get_preservesPitch: (obj) => obj.preservesPitch,
    set_preservesPitch: (obj, value) => { obj.preservesPitch = value; },
    get_played: (obj) => obj.played,
    get_seekable: (obj) => obj.seekable,
    get_ended: (obj) => obj.ended,
    get_autoplay: (obj) => obj.autoplay,
    set_autoplay: (obj, value) => { obj.autoplay = value; },
    get_loop: (obj) => obj.loop,
    set_loop: (obj, value) => { obj.loop = value; },
    get_controls: (obj) => obj.controls,
    set_controls: (obj, value) => { obj.controls = value; },
    get_volume: (obj) => obj.volume,
    set_volume: (obj, value) => { obj.volume = value; },
    get_muted: (obj) => obj.muted,
    set_muted: (obj, value) => { obj.muted = value; },
    get_defaultMuted: (obj) => obj.defaultMuted,
    set_defaultMuted: (obj, value) => { obj.defaultMuted = value; },
    get_audioTracks: (obj) => obj.audioTracks,
    get_videoTracks: (obj) => obj.videoTracks,
    get_textTracks: (obj) => obj.textTracks,
    load: (obj) => obj.load(),
    canPlayType: (obj, type_) => obj.canPlayType(type_),
    fastSeek: (obj, time) => obj.fastSeek(time),
    getStartDate: (obj) => obj.getStartDate(),
    play: (obj) => obj.play(),
    pause: (obj) => obj.pause(),
    addTextTrack: (obj, kind, label, language) => obj.addTextTrack(kind, label, language)
  },

  webapi_HTMLMapElement: {
    new: () => new HTMLMapElement(),
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_areas: (obj) => obj.areas
  },

  webapi_HTMLAreaElement: {
    new: () => new HTMLAreaElement(),
    get_alt: (obj) => obj.alt,
    set_alt: (obj, value) => { obj.alt = value; },
    get_coords: (obj) => obj.coords,
    set_coords: (obj, value) => { obj.coords = value; },
    get_shape: (obj) => obj.shape,
    set_shape: (obj, value) => { obj.shape = value; },
    get_target: (obj) => obj.target,
    set_target: (obj, value) => { obj.target = value; },
    get_download: (obj) => obj.download,
    set_download: (obj, value) => { obj.download = value; },
    get_ping: (obj) => obj.ping,
    set_ping: (obj, value) => { obj.ping = value; },
    get_rel: (obj) => obj.rel,
    set_rel: (obj, value) => { obj.rel = value; },
    get_relList: (obj) => obj.relList,
    get_referrerPolicy: (obj) => obj.referrerPolicy,
    set_referrerPolicy: (obj, value) => { obj.referrerPolicy = value; },
    get_noHref: (obj) => obj.noHref,
    set_noHref: (obj, value) => { obj.noHref = value; }
  },

  webapi_HTMLTableElement: {
    new: () => new HTMLTableElement(),
    get_caption: (obj) => obj.caption,
    set_caption: (obj, value) => { obj.caption = value; },
    get_tHead: (obj) => obj.tHead,
    set_tHead: (obj, value) => { obj.tHead = value; },
    get_tFoot: (obj) => obj.tFoot,
    set_tFoot: (obj, value) => { obj.tFoot = value; },
    get_tBodies: (obj) => obj.tBodies,
    get_rows: (obj) => obj.rows,
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_border: (obj) => obj.border,
    set_border: (obj, value) => { obj.border = value; },
    get_frame: (obj) => obj.frame,
    set_frame: (obj, value) => { obj.frame = value; },
    get_rules: (obj) => obj.rules,
    set_rules: (obj, value) => { obj.rules = value; },
    get_summary: (obj) => obj.summary,
    set_summary: (obj, value) => { obj.summary = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_bgColor: (obj) => obj.bgColor,
    set_bgColor: (obj, value) => { obj.bgColor = value; },
    get_cellPadding: (obj) => obj.cellPadding,
    set_cellPadding: (obj, value) => { obj.cellPadding = value; },
    get_cellSpacing: (obj) => obj.cellSpacing,
    set_cellSpacing: (obj, value) => { obj.cellSpacing = value; },
    createCaption: (obj) => obj.createCaption(),
    deleteCaption: (obj) => obj.deleteCaption(),
    createTHead: (obj) => obj.createTHead(),
    deleteTHead: (obj) => obj.deleteTHead(),
    createTFoot: (obj) => obj.createTFoot(),
    deleteTFoot: (obj) => obj.deleteTFoot(),
    createTBody: (obj) => obj.createTBody(),
    insertRow: (obj, index) => obj.insertRow(index),
    deleteRow: (obj, index) => obj.deleteRow(index)
  },

  webapi_HTMLTableCaptionElement: {
    new: () => new HTMLTableCaptionElement(),
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; }
  },

  webapi_HTMLTableColElement: {
    new: () => new HTMLTableColElement(),
    get_span: (obj) => obj.span,
    set_span: (obj, value) => { obj.span = value; },
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_ch: (obj) => obj.ch,
    set_ch: (obj, value) => { obj.ch = value; },
    get_chOff: (obj) => obj.chOff,
    set_chOff: (obj, value) => { obj.chOff = value; },
    get_vAlign: (obj) => obj.vAlign,
    set_vAlign: (obj, value) => { obj.vAlign = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; }
  },

  webapi_HTMLTableSectionElement: {
    new: () => new HTMLTableSectionElement(),
    get_rows: (obj) => obj.rows,
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_ch: (obj) => obj.ch,
    set_ch: (obj, value) => { obj.ch = value; },
    get_chOff: (obj) => obj.chOff,
    set_chOff: (obj, value) => { obj.chOff = value; },
    get_vAlign: (obj) => obj.vAlign,
    set_vAlign: (obj, value) => { obj.vAlign = value; },
    insertRow: (obj, index) => obj.insertRow(index),
    deleteRow: (obj, index) => obj.deleteRow(index)
  },

  webapi_HTMLTableRowElement: {
    new: () => new HTMLTableRowElement(),
    get_rowIndex: (obj) => obj.rowIndex,
    get_sectionRowIndex: (obj) => obj.sectionRowIndex,
    get_cells: (obj) => obj.cells,
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_ch: (obj) => obj.ch,
    set_ch: (obj, value) => { obj.ch = value; },
    get_chOff: (obj) => obj.chOff,
    set_chOff: (obj, value) => { obj.chOff = value; },
    get_vAlign: (obj) => obj.vAlign,
    set_vAlign: (obj, value) => { obj.vAlign = value; },
    get_bgColor: (obj) => obj.bgColor,
    set_bgColor: (obj, value) => { obj.bgColor = value; },
    insertCell: (obj, index) => obj.insertCell(index),
    deleteCell: (obj, index) => obj.deleteCell(index)
  },

  webapi_HTMLTableCellElement: {
    new: () => new HTMLTableCellElement(),
    get_colSpan: (obj) => obj.colSpan,
    set_colSpan: (obj, value) => { obj.colSpan = value; },
    get_rowSpan: (obj) => obj.rowSpan,
    set_rowSpan: (obj, value) => { obj.rowSpan = value; },
    get_headers: (obj) => obj.headers,
    set_headers: (obj, value) => { obj.headers = value; },
    get_cellIndex: (obj) => obj.cellIndex,
    get_scope: (obj) => obj.scope,
    set_scope: (obj, value) => { obj.scope = value; },
    get_abbr: (obj) => obj.abbr,
    set_abbr: (obj, value) => { obj.abbr = value; },
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_axis: (obj) => obj.axis,
    set_axis: (obj, value) => { obj.axis = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_ch: (obj) => obj.ch,
    set_ch: (obj, value) => { obj.ch = value; },
    get_chOff: (obj) => obj.chOff,
    set_chOff: (obj, value) => { obj.chOff = value; },
    get_noWrap: (obj) => obj.noWrap,
    set_noWrap: (obj, value) => { obj.noWrap = value; },
    get_vAlign: (obj) => obj.vAlign,
    set_vAlign: (obj, value) => { obj.vAlign = value; },
    get_bgColor: (obj) => obj.bgColor,
    set_bgColor: (obj, value) => { obj.bgColor = value; }
  },

  webapi_HTMLFormElement: {
    new: () => new HTMLFormElement(),
    get_acceptCharset: (obj) => obj.acceptCharset,
    set_acceptCharset: (obj, value) => { obj.acceptCharset = value; },
    get_action: (obj) => obj.action,
    set_action: (obj, value) => { obj.action = value; },
    get_autocomplete: (obj) => obj.autocomplete,
    set_autocomplete: (obj, value) => { obj.autocomplete = value; },
    get_enctype: (obj) => obj.enctype,
    set_enctype: (obj, value) => { obj.enctype = value; },
    get_encoding: (obj) => obj.encoding,
    set_encoding: (obj, value) => { obj.encoding = value; },
    get_method: (obj) => obj.method,
    set_method: (obj, value) => { obj.method = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_noValidate: (obj) => obj.noValidate,
    set_noValidate: (obj, value) => { obj.noValidate = value; },
    get_target: (obj) => obj.target,
    set_target: (obj, value) => { obj.target = value; },
    get_rel: (obj) => obj.rel,
    set_rel: (obj, value) => { obj.rel = value; },
    get_relList: (obj) => obj.relList,
    get_elements: (obj) => obj.elements,
    get_length: (obj) => obj.length,
    submit: (obj) => obj.submit(),
    requestSubmit: (obj, submitter) => obj.requestSubmit(submitter),
    reset: (obj) => obj.reset(),
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity()
  },

  webapi_HTMLLabelElement: {
    new: () => new HTMLLabelElement(),
    get_form: (obj) => obj.form,
    get_htmlFor: (obj) => obj.htmlFor,
    set_htmlFor: (obj, value) => { obj.htmlFor = value; },
    get_control: (obj) => obj.control
  },

  webapi_HTMLInputElement: {
    new: () => new HTMLInputElement(),
    get_accept: (obj) => obj.accept,
    set_accept: (obj, value) => { obj.accept = value; },
    get_alpha: (obj) => obj.alpha,
    set_alpha: (obj, value) => { obj.alpha = value; },
    get_alt: (obj) => obj.alt,
    set_alt: (obj, value) => { obj.alt = value; },
    get_autocomplete: (obj) => obj.autocomplete,
    set_autocomplete: (obj, value) => { obj.autocomplete = value; },
    get_defaultChecked: (obj) => obj.defaultChecked,
    set_defaultChecked: (obj, value) => { obj.defaultChecked = value; },
    get_checked: (obj) => obj.checked,
    set_checked: (obj, value) => { obj.checked = value; },
    get_colorSpace: (obj) => obj.colorSpace,
    set_colorSpace: (obj, value) => { obj.colorSpace = value; },
    get_dirName: (obj) => obj.dirName,
    set_dirName: (obj, value) => { obj.dirName = value; },
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_form: (obj) => obj.form,
    get_files: (obj) => obj.files,
    set_files: (obj, value) => { obj.files = value; },
    get_formAction: (obj) => obj.formAction,
    set_formAction: (obj, value) => { obj.formAction = value; },
    get_formEnctype: (obj) => obj.formEnctype,
    set_formEnctype: (obj, value) => { obj.formEnctype = value; },
    get_formMethod: (obj) => obj.formMethod,
    set_formMethod: (obj, value) => { obj.formMethod = value; },
    get_formNoValidate: (obj) => obj.formNoValidate,
    set_formNoValidate: (obj, value) => { obj.formNoValidate = value; },
    get_formTarget: (obj) => obj.formTarget,
    set_formTarget: (obj, value) => { obj.formTarget = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_indeterminate: (obj) => obj.indeterminate,
    set_indeterminate: (obj, value) => { obj.indeterminate = value; },
    get_list: (obj) => obj.list,
    get_max: (obj) => obj.max,
    set_max: (obj, value) => { obj.max = value; },
    get_maxLength: (obj) => obj.maxLength,
    set_maxLength: (obj, value) => { obj.maxLength = value; },
    get_min: (obj) => obj.min,
    set_min: (obj, value) => { obj.min = value; },
    get_minLength: (obj) => obj.minLength,
    set_minLength: (obj, value) => { obj.minLength = value; },
    get_multiple: (obj) => obj.multiple,
    set_multiple: (obj, value) => { obj.multiple = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_pattern: (obj) => obj.pattern,
    set_pattern: (obj, value) => { obj.pattern = value; },
    get_placeholder: (obj) => obj.placeholder,
    set_placeholder: (obj, value) => { obj.placeholder = value; },
    get_readOnly: (obj) => obj.readOnly,
    set_readOnly: (obj, value) => { obj.readOnly = value; },
    get_required: (obj) => obj.required,
    set_required: (obj, value) => { obj.required = value; },
    get_size: (obj) => obj.size,
    set_size: (obj, value) => { obj.size = value; },
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_step: (obj) => obj.step,
    set_step: (obj, value) => { obj.step = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_defaultValue: (obj) => obj.defaultValue,
    set_defaultValue: (obj, value) => { obj.defaultValue = value; },
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_valueAsDate: (obj) => obj.valueAsDate,
    set_valueAsDate: (obj, value) => { obj.valueAsDate = value; },
    get_valueAsNumber: (obj) => obj.valueAsNumber,
    set_valueAsNumber: (obj, value) => { obj.valueAsNumber = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_willValidate: (obj) => obj.willValidate,
    get_validity: (obj) => obj.validity,
    get_validationMessage: (obj) => obj.validationMessage,
    get_labels: (obj) => obj.labels,
    get_selectionStart: (obj) => obj.selectionStart,
    set_selectionStart: (obj, value) => { obj.selectionStart = value; },
    get_selectionEnd: (obj) => obj.selectionEnd,
    set_selectionEnd: (obj, value) => { obj.selectionEnd = value; },
    get_selectionDirection: (obj) => obj.selectionDirection,
    set_selectionDirection: (obj, value) => { obj.selectionDirection = value; },
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; },
    get_useMap: (obj) => obj.useMap,
    set_useMap: (obj, value) => { obj.useMap = value; },
    stepUp: (obj, n) => obj.stepUp(n),
    stepDown: (obj, n) => obj.stepDown(n),
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity(),
    setCustomValidity: (obj, error) => obj.setCustomValidity(error),
    select: (obj) => obj.select(),
    setRangeText: (obj, replacement) => obj.setRangeText(replacement),
    setRangeText: (obj, replacement, start, end, selection_mode) => obj.setRangeText(replacement, start, end, selection_mode),
    setSelectionRange: (obj, start, end, direction) => obj.setSelectionRange(start, end, direction),
    showPicker: (obj) => obj.showPicker()
  },

  webapi_HTMLButtonElement: {
    new: () => new HTMLButtonElement(),
    get_command: (obj) => obj.command,
    set_command: (obj, value) => { obj.command = value; },
    get_commandForElement: (obj) => obj.commandForElement,
    set_commandForElement: (obj, value) => { obj.commandForElement = value; },
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_form: (obj) => obj.form,
    get_formAction: (obj) => obj.formAction,
    set_formAction: (obj, value) => { obj.formAction = value; },
    get_formEnctype: (obj) => obj.formEnctype,
    set_formEnctype: (obj, value) => { obj.formEnctype = value; },
    get_formMethod: (obj) => obj.formMethod,
    set_formMethod: (obj, value) => { obj.formMethod = value; },
    get_formNoValidate: (obj) => obj.formNoValidate,
    set_formNoValidate: (obj, value) => { obj.formNoValidate = value; },
    get_formTarget: (obj) => obj.formTarget,
    set_formTarget: (obj, value) => { obj.formTarget = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_willValidate: (obj) => obj.willValidate,
    get_validity: (obj) => obj.validity,
    get_validationMessage: (obj) => obj.validationMessage,
    get_labels: (obj) => obj.labels,
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity(),
    setCustomValidity: (obj, error) => obj.setCustomValidity(error)
  },

  webapi_HTMLSelectElement: {
    new: () => new HTMLSelectElement(),
    get_autocomplete: (obj) => obj.autocomplete,
    set_autocomplete: (obj, value) => { obj.autocomplete = value; },
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_form: (obj) => obj.form,
    get_multiple: (obj) => obj.multiple,
    set_multiple: (obj, value) => { obj.multiple = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_required: (obj) => obj.required,
    set_required: (obj, value) => { obj.required = value; },
    get_size: (obj) => obj.size,
    set_size: (obj, value) => { obj.size = value; },
    get_type: (obj) => obj.type,
    get_options: (obj) => obj.options,
    get_length: (obj) => obj.length,
    set_length: (obj, value) => { obj.length = value; },
    get_selectedOptions: (obj) => obj.selectedOptions,
    get_selectedIndex: (obj) => obj.selectedIndex,
    set_selectedIndex: (obj, value) => { obj.selectedIndex = value; },
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_willValidate: (obj) => obj.willValidate,
    get_validity: (obj) => obj.validity,
    get_validationMessage: (obj) => obj.validationMessage,
    get_labels: (obj) => obj.labels,
    namedItem: (obj, name) => obj.namedItem(name),
    add: (obj, element, before) => obj.add(element, before),
    remove: (obj) => obj.remove(),
    remove: (obj, index) => obj.remove(index),
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity(),
    setCustomValidity: (obj, error) => obj.setCustomValidity(error),
    showPicker: (obj) => obj.showPicker()
  },

  webapi_HTMLDataListElement: {
    new: () => new HTMLDataListElement(),
    get_options: (obj) => obj.options
  },

  webapi_HTMLOptGroupElement: {
    new: () => new HTMLOptGroupElement(),
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_label: (obj) => obj.label,
    set_label: (obj, value) => { obj.label = value; }
  },

  webapi_HTMLOptionElement: {
    new: () => new HTMLOptionElement(),
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_form: (obj) => obj.form,
    get_label: (obj) => obj.label,
    set_label: (obj, value) => { obj.label = value; },
    get_defaultSelected: (obj) => obj.defaultSelected,
    set_defaultSelected: (obj, value) => { obj.defaultSelected = value; },
    get_selected: (obj) => obj.selected,
    set_selected: (obj, value) => { obj.selected = value; },
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_text: (obj) => obj.text,
    set_text: (obj, value) => { obj.text = value; },
    get_index: (obj) => obj.index
  },

  webapi_HTMLTextAreaElement: {
    new: () => new HTMLTextAreaElement(),
    get_autocomplete: (obj) => obj.autocomplete,
    set_autocomplete: (obj, value) => { obj.autocomplete = value; },
    get_cols: (obj) => obj.cols,
    set_cols: (obj, value) => { obj.cols = value; },
    get_dirName: (obj) => obj.dirName,
    set_dirName: (obj, value) => { obj.dirName = value; },
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_form: (obj) => obj.form,
    get_maxLength: (obj) => obj.maxLength,
    set_maxLength: (obj, value) => { obj.maxLength = value; },
    get_minLength: (obj) => obj.minLength,
    set_minLength: (obj, value) => { obj.minLength = value; },
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_placeholder: (obj) => obj.placeholder,
    set_placeholder: (obj, value) => { obj.placeholder = value; },
    get_readOnly: (obj) => obj.readOnly,
    set_readOnly: (obj, value) => { obj.readOnly = value; },
    get_required: (obj) => obj.required,
    set_required: (obj, value) => { obj.required = value; },
    get_rows: (obj) => obj.rows,
    set_rows: (obj, value) => { obj.rows = value; },
    get_wrap: (obj) => obj.wrap,
    set_wrap: (obj, value) => { obj.wrap = value; },
    get_type: (obj) => obj.type,
    get_defaultValue: (obj) => obj.defaultValue,
    set_defaultValue: (obj, value) => { obj.defaultValue = value; },
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_textLength: (obj) => obj.textLength,
    get_willValidate: (obj) => obj.willValidate,
    get_validity: (obj) => obj.validity,
    get_validationMessage: (obj) => obj.validationMessage,
    get_labels: (obj) => obj.labels,
    get_selectionStart: (obj) => obj.selectionStart,
    set_selectionStart: (obj, value) => { obj.selectionStart = value; },
    get_selectionEnd: (obj) => obj.selectionEnd,
    set_selectionEnd: (obj, value) => { obj.selectionEnd = value; },
    get_selectionDirection: (obj) => obj.selectionDirection,
    set_selectionDirection: (obj, value) => { obj.selectionDirection = value; },
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity(),
    setCustomValidity: (obj, error) => obj.setCustomValidity(error),
    select: (obj) => obj.select(),
    setRangeText: (obj, replacement) => obj.setRangeText(replacement),
    setRangeText: (obj, replacement, start, end, selection_mode) => obj.setRangeText(replacement, start, end, selection_mode),
    setSelectionRange: (obj, start, end, direction) => obj.setSelectionRange(start, end, direction)
  },

  webapi_HTMLOutputElement: {
    new: () => new HTMLOutputElement(),
    get_htmlFor: (obj) => obj.htmlFor,
    get_form: (obj) => obj.form,
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_type: (obj) => obj.type,
    get_defaultValue: (obj) => obj.defaultValue,
    set_defaultValue: (obj, value) => { obj.defaultValue = value; },
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_willValidate: (obj) => obj.willValidate,
    get_validity: (obj) => obj.validity,
    get_validationMessage: (obj) => obj.validationMessage,
    get_labels: (obj) => obj.labels,
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity(),
    setCustomValidity: (obj, error) => obj.setCustomValidity(error)
  },

  webapi_HTMLProgressElement: {
    new: () => new HTMLProgressElement(),
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_max: (obj) => obj.max,
    set_max: (obj, value) => { obj.max = value; },
    get_position: (obj) => obj.position,
    get_labels: (obj) => obj.labels
  },

  webapi_HTMLMeterElement: {
    new: () => new HTMLMeterElement(),
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_min: (obj) => obj.min,
    set_min: (obj, value) => { obj.min = value; },
    get_max: (obj) => obj.max,
    set_max: (obj, value) => { obj.max = value; },
    get_low: (obj) => obj.low,
    set_low: (obj, value) => { obj.low = value; },
    get_high: (obj) => obj.high,
    set_high: (obj, value) => { obj.high = value; },
    get_optimum: (obj) => obj.optimum,
    set_optimum: (obj, value) => { obj.optimum = value; },
    get_labels: (obj) => obj.labels
  },

  webapi_HTMLFieldSetElement: {
    new: () => new HTMLFieldSetElement(),
    get_disabled: (obj) => obj.disabled,
    set_disabled: (obj, value) => { obj.disabled = value; },
    get_form: (obj) => obj.form,
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_type: (obj) => obj.type,
    get_elements: (obj) => obj.elements,
    get_willValidate: (obj) => obj.willValidate,
    get_validity: (obj) => obj.validity,
    get_validationMessage: (obj) => obj.validationMessage,
    checkValidity: (obj) => obj.checkValidity(),
    reportValidity: (obj) => obj.reportValidity(),
    setCustomValidity: (obj, error) => obj.setCustomValidity(error)
  },

  webapi_HTMLLegendElement: {
    new: () => new HTMLLegendElement(),
    get_form: (obj) => obj.form,
    get_align: (obj) => obj.align,
    set_align: (obj, value) => { obj.align = value; }
  },

  webapi_HTMLDetailsElement: {
    new: () => new HTMLDetailsElement(),
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_open: (obj) => obj.open,
    set_open: (obj, value) => { obj.open = value; }
  },

  webapi_HTMLDialogElement: {
    new: () => new HTMLDialogElement(),
    get_open: (obj) => obj.open,
    set_open: (obj, value) => { obj.open = value; },
    get_returnValue: (obj) => obj.returnValue,
    set_returnValue: (obj, value) => { obj.returnValue = value; },
    get_closedBy: (obj) => obj.closedBy,
    set_closedBy: (obj, value) => { obj.closedBy = value; },
    show: (obj) => obj.show(),
    showModal: (obj) => obj.showModal(),
    close: (obj, return_value) => obj.close(return_value),
    requestClose: (obj, return_value) => obj.requestClose(return_value)
  },

  webapi_HTMLScriptElement: {
    new: () => new HTMLScriptElement(),
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_noModule: (obj) => obj.noModule,
    set_noModule: (obj, value) => { obj.noModule = value; },
    get_async: (obj) => obj.async,
    set_async: (obj, value) => { obj.async = value; },
    get_defer: (obj) => obj.defer,
    set_defer: (obj, value) => { obj.defer = value; },
    get_blocking: (obj) => obj.blocking,
    get_crossOrigin: (obj) => obj.crossOrigin,
    set_crossOrigin: (obj, value) => { obj.crossOrigin = value; },
    get_referrerPolicy: (obj) => obj.referrerPolicy,
    set_referrerPolicy: (obj, value) => { obj.referrerPolicy = value; },
    get_integrity: (obj) => obj.integrity,
    set_integrity: (obj, value) => { obj.integrity = value; },
    get_fetchPriority: (obj) => obj.fetchPriority,
    set_fetchPriority: (obj, value) => { obj.fetchPriority = value; },
    get_text: (obj) => obj.text,
    set_text: (obj, value) => { obj.text = value; },
    get_charset: (obj) => obj.charset,
    set_charset: (obj, value) => { obj.charset = value; },
    get_event: (obj) => obj.event,
    set_event: (obj, value) => { obj.event = value; },
    get_htmlFor: (obj) => obj.htmlFor,
    set_htmlFor: (obj, value) => { obj.htmlFor = value; },
    supports: (type_) => supports(type_)
  },

  webapi_HTMLTemplateElement: {
    new: () => new HTMLTemplateElement(),
    get_content: (obj) => obj.content,
    get_shadowRootMode: (obj) => obj.shadowRootMode,
    set_shadowRootMode: (obj, value) => { obj.shadowRootMode = value; },
    get_shadowRootDelegatesFocus: (obj) => obj.shadowRootDelegatesFocus,
    set_shadowRootDelegatesFocus: (obj, value) => { obj.shadowRootDelegatesFocus = value; },
    get_shadowRootClonable: (obj) => obj.shadowRootClonable,
    set_shadowRootClonable: (obj, value) => { obj.shadowRootClonable = value; },
    get_shadowRootSerializable: (obj) => obj.shadowRootSerializable,
    set_shadowRootSerializable: (obj, value) => { obj.shadowRootSerializable = value; },
    get_shadowRootCustomElementRegistry: (obj) => obj.shadowRootCustomElementRegistry,
    set_shadowRootCustomElementRegistry: (obj, value) => { obj.shadowRootCustomElementRegistry = value; }
  },

  webapi_HTMLSlotElement: {
    new: () => new HTMLSlotElement(),
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    assignedNodes: (obj, options) => obj.assignedNodes(options),
    assignedElements: (obj, options) => obj.assignedElements(options),
    assign: (obj, nodes) => obj.assign(nodes)
  },

  webapi_HTMLCanvasElement: {
    new: () => new HTMLCanvasElement(),
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    getContext: (obj, context_id, options) => obj.getContext(context_id, options),
    toDataURL: (obj, type_, quality) => obj.toDataURL(type_, quality),
    toBlob: (obj, _callback, type_, quality) => obj.toBlob(_callback, type_, quality),
    transferControlToOffscreen: (obj) => obj.transferControlToOffscreen()
  },

  webapi_HTMLMarqueeElement: {
    new: () => new HTMLMarqueeElement(),
    get_behavior: (obj) => obj.behavior,
    set_behavior: (obj, value) => { obj.behavior = value; },
    get_bgColor: (obj) => obj.bgColor,
    set_bgColor: (obj, value) => { obj.bgColor = value; },
    get_direction: (obj) => obj.direction,
    set_direction: (obj, value) => { obj.direction = value; },
    get_height: (obj) => obj.height,
    set_height: (obj, value) => { obj.height = value; },
    get_hspace: (obj) => obj.hspace,
    set_hspace: (obj, value) => { obj.hspace = value; },
    get_loop: (obj) => obj.loop,
    set_loop: (obj, value) => { obj.loop = value; },
    get_scrollAmount: (obj) => obj.scrollAmount,
    set_scrollAmount: (obj, value) => { obj.scrollAmount = value; },
    get_scrollDelay: (obj) => obj.scrollDelay,
    set_scrollDelay: (obj, value) => { obj.scrollDelay = value; },
    get_trueSpeed: (obj) => obj.trueSpeed,
    set_trueSpeed: (obj, value) => { obj.trueSpeed = value; },
    get_vspace: (obj) => obj.vspace,
    set_vspace: (obj, value) => { obj.vspace = value; },
    get_width: (obj) => obj.width,
    set_width: (obj, value) => { obj.width = value; },
    start: (obj) => obj.start(),
    stop: (obj) => obj.stop()
  },

  webapi_HTMLFrameSetElement: {
    new: () => new HTMLFrameSetElement(),
    get_cols: (obj) => obj.cols,
    set_cols: (obj, value) => { obj.cols = value; },
    get_rows: (obj) => obj.rows,
    set_rows: (obj, value) => { obj.rows = value; }
  },

  webapi_HTMLFrameElement: {
    new: () => new HTMLFrameElement(),
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_scrolling: (obj) => obj.scrolling,
    set_scrolling: (obj, value) => { obj.scrolling = value; },
    get_src: (obj) => obj.src,
    set_src: (obj, value) => { obj.src = value; },
    get_frameBorder: (obj) => obj.frameBorder,
    set_frameBorder: (obj, value) => { obj.frameBorder = value; },
    get_longDesc: (obj) => obj.longDesc,
    set_longDesc: (obj, value) => { obj.longDesc = value; },
    get_noResize: (obj) => obj.noResize,
    set_noResize: (obj, value) => { obj.noResize = value; },
    get_contentDocument: (obj) => obj.contentDocument,
    get_contentWindow: (obj) => obj.contentWindow,
    get_marginHeight: (obj) => obj.marginHeight,
    set_marginHeight: (obj, value) => { obj.marginHeight = value; },
    get_marginWidth: (obj) => obj.marginWidth,
    set_marginWidth: (obj, value) => { obj.marginWidth = value; }
  },

  webapi_HTMLDirectoryElement: {
    new: () => new HTMLDirectoryElement(),
    get_compact: (obj) => obj.compact,
    set_compact: (obj, value) => { obj.compact = value; }
  },

  webapi_HTMLFontElement: {
    new: () => new HTMLFontElement(),
    get_color: (obj) => obj.color,
    set_color: (obj, value) => { obj.color = value; },
    get_face: (obj) => obj.face,
    set_face: (obj, value) => { obj.face = value; },
    get_size: (obj) => obj.size,
    set_size: (obj, value) => { obj.size = value; }
  },

  webapi_HTMLParamElement: {
    new: () => new HTMLParamElement(),
    get_name: (obj) => obj.name,
    set_name: (obj, value) => { obj.name = value; },
    get_value: (obj) => obj.value,
    set_value: (obj, value) => { obj.value = value; },
    get_type: (obj) => obj.type,
    set_type: (obj, value) => { obj.type = value; },
    get_valueType: (obj) => obj.valueType,
    set_valueType: (obj, value) => { obj.valueType = value; }
  }
};
